"""
Django admin configuration for users, profiles, sessions, OTP records, and auth risk.

UX design:
- «کاربران» مرکز اصلی مشاهده/ویرایش هویت و پروفایل کاربر است.
- Profile به‌عنوان داده‌ی تکمیلی مستقیم کاربر داخل صفحه User مدیریت می‌شود و از
  index اصلی ادمین مخفی است.
- نشست‌ها و سیگنال‌های ریسک هم داخل صفحه User به‌صورت read-only دیده می‌شوند،
  اما صفحات امنیتی جداگانه‌شان همچنان در index باقی می‌مانند.
- OTPCode فعلاً در index باقی می‌ماند تا تا زمان اتصال کامل پنل پیامکی، تست و
  پشتیبانی عملیاتی ساده‌تر باشد. کد خام همچنان ذخیره/نمایش داده نمی‌شود؛ فقط hash
  و metadata قابل مشاهده است.
"""

from __future__ import annotations

from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as DjangoUserAdmin
from django.utils.html import format_html

from .models import AuthRiskSignal, AuthSession, OTPCode, Profile, User


class HiddenFromAdminIndexMixin:
    """Keep a ModelAdmin registered but hide it from the admin index/app list."""

    def get_model_perms(self, request) -> dict[str, bool]:
        """Return no perms so Django omits this model from the admin index."""
        return {}


class ProfileInline(admin.StackedInline):
    """Inline profile fields in the main user workspace."""

    model = Profile
    can_delete = False
    extra = 0
    fields = (
        "national_code",
        "birth_date",
        "gender",
        "avatar",
        "bio",
        "province",
        "city",
        "address",
        "r4j_completeness_display",
        "created_at",
        "updated_at",
    )
    readonly_fields = ("r4j_completeness_display", "created_at", "updated_at")

    @admin.display(description="تکمیل پروفایل برای عملیات حساس")
    def r4j_completeness_display(self, obj: Profile) -> str:
        """Show whether the profile satisfies high-trust R4J requirements."""
        if obj is None or obj.pk is None:
            return "پس از ایجاد پروفایل محاسبه می‌شود."
        missing = obj.get_missing_r4j_fields()
        if not missing:
            return format_html('<strong style="color: green;">کامل</strong>')
        return format_html(
            '<strong style="color: orange;">ناقص</strong> — فیلدهای ناقص: {}',
            ", ".join(missing),
        )


class AuthSessionInline(admin.TabularInline):
    """Read-only recent sessions/devices in the user workspace."""

    model = AuthSession
    extra = 0
    can_delete = False
    fields = (
        "device_label",
        "ip_address",
        "is_revoked",
        "last_seen_at",
        "expires_at",
        "revoked_at",
    )
    readonly_fields = fields
    ordering = ("-last_seen_at", "-created_at")
    show_change_link = True

    def has_add_permission(self, request, obj=None) -> bool:
        """Sessions are created by login services."""
        return False

    def has_change_permission(self, request, obj=None) -> bool:
        """Session mutation/revocation must go through audited services/APIs."""
        return False

    def has_delete_permission(self, request, obj=None) -> bool:
        """Session evidence should remain available for security review."""
        return False


class AuthRiskSignalInline(admin.TabularInline):
    """Read-only auth risk signals in the user workspace."""

    model = AuthRiskSignal
    extra = 0
    can_delete = False
    fields = (
        "signal_type",
        "severity",
        "status",
        "ip_address",
        "description",
        "reviewed_by",
        "reviewed_at",
        "created_at",
    )
    readonly_fields = fields
    ordering = ("-created_at",)
    show_change_link = True

    def has_add_permission(self, request, obj=None) -> bool:
        """Risk signals are generated by authentication/security services."""
        return False

    def has_change_permission(self, request, obj=None) -> bool:
        """Risk review must go through audited services/APIs."""
        return False

    def has_delete_permission(self, request, obj=None) -> bool:
        """Risk evidence should remain available for security review."""
        return False


@admin.register(User)
class UserAdmin(DjangoUserAdmin):
    """
    UserAdmin سفارشی هماهنگ با multi-identifier model.

    - email و phone_number هر دو در list_display و search_fields هستند.
    - primary_identifier نشان می‌دهد کاربر در ابتدا/اکنون با کدام channel اصلی
      کار می‌کند.
    - Profile، نشست‌ها و risk signals در صفحه کاربر تجمیع شده‌اند.
    - صفحات امنیتی نشست و risk signal همچنان جداگانه باقی می‌مانند.
    """

    ordering = ("-date_joined",)
    list_display = (
        "email",
        "phone_number",
        "primary_identifier",
        "first_name",
        "last_name",
        "role",
        "is_active",
        "is_email_verified",
        "is_phone_verified",
        "date_joined",
    )
    list_filter = (
        "role",
        "primary_identifier",
        "is_active",
        "is_email_verified",
        "is_phone_verified",
        "is_staff",
    )
    search_fields = ("email", "phone_number", "first_name", "last_name")
    readonly_fields = ("date_joined", "last_login", "last_login_ip", "verification_summary")
    inlines = [ProfileInline, AuthSessionInline, AuthRiskSignalInline]

    fieldsets = (
        (None, {"fields": ("email", "phone_number", "primary_identifier", "password")}),
        ("اطلاعات شخصی", {"fields": ("first_name", "last_name")}),
        (
            "نقش و دسترسی",
            {
                "fields": (
                    "role",
                    "is_active",
                    "is_staff",
                    "is_superuser",
                    "is_email_verified",
                    "is_phone_verified",
                    "verification_summary",
                    "groups",
                    "user_permissions",
                )
            },
        ),
        ("اطلاعات سیستم", {"fields": ("date_joined", "last_login", "last_login_ip")}),
    )

    add_fieldsets = (
        (
            None,
            {
                "classes": ("wide",),
                "fields": (
                    "email",
                    "password1",
                    "password2",
                    "role",
                    "is_staff",
                    "is_active",
                ),
            },
        ),
    )

    @admin.display(description="وضعیت احراز هویت")
    def verification_summary(self, obj: User) -> str:
        """Compact verification summary for admin reviewers."""
        if obj is None or obj.pk is None:
            return "پس از ایجاد کاربر محاسبه می‌شود."
        status = "کامل" if obj.is_fully_verified else "ناقص"
        color = "green" if obj.is_fully_verified else "orange"
        return format_html(
            '<strong style="color: {};">{}</strong> — ایمیل: {}، موبایل: {}',
            color,
            status,
            "تأیید" if obj.is_email_verified else "تأیید نشده",
            "تأیید" if obj.is_phone_verified else "تأیید نشده",
        )


@admin.register(Profile)
class ProfileAdmin(HiddenFromAdminIndexMixin, admin.ModelAdmin):
    """Profile admin kept for direct links/debug but hidden from top-level index."""

    list_display = ("user", "national_code", "city", "is_complete_for_r4j_display")
    search_fields = ("user__email", "user__phone_number", "national_code")
    raw_id_fields = ("user",)
    readonly_fields = ("created_at", "updated_at", "is_complete_for_r4j_display")

    @admin.display(description="کامل برای R4J")
    def is_complete_for_r4j_display(self, obj: Profile) -> bool:
        """Boolean display for high-trust profile completeness."""
        return obj.is_complete_for_r4j


@admin.register(OTPCode)
class OTPCodeAdmin(admin.ModelAdmin):
    """
    OTPCodeAdmin برای پشتیبانی عملیاتی تا قبل از اتصال کامل پنل پیامکی.

    - OTP plain هرگز ذخیره/نمایش داده نمی‌شود؛ فقط code_hash و metadata قابل مشاهده است.
    - صفحه OTP عمداً در index باقی می‌ماند تا در تست دستی بتوان وضعیت OTPها را دید.
    """

    list_display = (
        "identifier_kind",
        "identifier_value",
        "purpose",
        "attempts",
        "is_used",
        "is_expired_display",
        "expires_at",
        "created_at",
    )
    list_filter = ("identifier_kind", "purpose", "is_used")
    search_fields = ("identifier_value",)
    readonly_fields = (
        "identifier_kind",
        "identifier_value",
        "purpose",
        "code_hash",
        "expires_at",
        "attempts",
        "is_used",
        "created_at",
        "updated_at",
    )
    ordering = ("-created_at",)

    @admin.display(description="منقضی شده", boolean=True)
    def is_expired_display(self, obj: OTPCode) -> bool:
        """Expose expiry as a boolean column without showing the raw OTP."""
        return obj.is_expired

    def has_add_permission(self, request) -> bool:
        """OTP records must be generated by auth services."""
        return False

    def has_change_permission(self, request, obj=None) -> bool:
        """OTP metadata is operational evidence and should not be edited."""
        return False

    def has_delete_permission(self, request, obj=None) -> bool:
        """OTP records should remain available during debugging/support windows."""
        return False


@admin.register(AuthSession)
class AuthSessionAdmin(admin.ModelAdmin):
    """Read-oriented standalone security admin for tracked auth sessions/devices."""

    list_display = ("id", "user", "device_label", "ip_address", "is_revoked", "last_seen_at", "expires_at")
    list_filter = ("is_revoked", "device_label")
    search_fields = ("user__email", "user__phone_number", "refresh_jti", "ip_address", "user_agent")
    readonly_fields = [field.name for field in AuthSession._meta.fields]
    raw_id_fields = ("user", "revoked_by")
    ordering = ("-last_seen_at", "-created_at")

    def has_add_permission(self, request) -> bool:
        """Sessions are created by login services."""
        return False

    def has_change_permission(self, request, obj=None) -> bool:
        """Session revocation must use audited APIs/services."""
        return False

    def has_delete_permission(self, request, obj=None) -> bool:
        """Session evidence should remain available for security review."""
        return False


@admin.register(AuthRiskSignal)
class AuthRiskSignalAdmin(admin.ModelAdmin):
    """Read-oriented standalone security admin for authentication risk signals."""

    list_display = ("id", "signal_type", "severity", "status", "user", "ip_address", "created_at")
    list_filter = ("signal_type", "severity", "status")
    search_fields = ("user__email", "user__phone_number", "ip_address", "description")
    readonly_fields = [field.name for field in AuthRiskSignal._meta.fields]
    raw_id_fields = ("user", "session", "reviewed_by")
    ordering = ("-created_at",)

    def has_add_permission(self, request) -> bool:
        """Risk signals are generated by auth services."""
        return False

    def has_change_permission(self, request, obj=None) -> bool:
        """Risk review must use audited API/service workflow."""
        return False

    def has_delete_permission(self, request, obj=None) -> bool:
        """Risk evidence should remain available for security review."""
        return False
