# Generated by Django 6.0.5 on 2026-06-11 11:50

import apps.kindness_wall.models
import apps.kindness_wall.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KindnessTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=160, unique=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'تگ دیوار مهربانی',
                'verbose_name_plural': 'تگ\u200cهای دیوار مهربانی',
                'ordering': ['normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='KindnessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان دسته')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=80, verbose_name='آیکن')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.kindness_wall.models.category_cover_upload_path, verbose_name='تصویر کاور')),
                ('path', models.CharField(blank=True, db_index=True, max_length=600, unique=True)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('listings_count', models.PositiveIntegerField(default=0)),
                ('published_listings_count', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='kindness_wall.kindnesscategory', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی دیوار مهربانی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای دیوار مهربانی',
                'ordering': ['depth', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KindnessKeywordAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('keyword', models.CharField(max_length=120)),
                ('alias', models.CharField(max_length=120)),
                ('normalized_keyword', models.CharField(db_index=True, max_length=160)),
                ('normalized_alias', models.CharField(db_index=True, max_length=160)),
            ],
            options={
                'verbose_name': 'هم\u200cمعنی جستجوی دیوار مهربانی',
                'verbose_name_plural': 'هم\u200cمعنی\u200cهای جستجوی دیوار مهربانی',
                'constraints': [models.UniqueConstraint(fields=('normalized_keyword', 'normalized_alias'), name='uniq_kindness_keyword_alias')],
            },
        ),
        migrations.CreateModel(
            name='KindnessListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('listing_type', models.CharField(choices=[('need_help', 'نیاز به کمک دارم'), ('offer_help', 'می\u200cخواهم کمک کنم')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=260)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=320, unique=True)),
                ('description', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('address_hint', models.CharField(blank=True, max_length=260)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_phone_snapshot', models.CharField(max_length=30)),
                ('owner_full_name_snapshot', models.CharField(max_length=260)),
                ('owner_avatar_snapshot', models.CharField(blank=True, max_length=512)),
                ('owner_gender_snapshot', models.CharField(blank=True, max_length=20)),
                ('owner_province_snapshot', models.CharField(blank=True, max_length=100)),
                ('owner_city_snapshot', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار بررسی'), ('published', 'منتشرشده'), ('rejected', 'ردشده'), ('needs_edit', 'نیازمند ویرایش'), ('suspended', 'تعلیق\u200cشده'), ('closed', 'بسته\u200cشده'), ('expired', 'منقضی\u200cشده'), ('deleted', 'حذف\u200cشده')], db_index=True, default='draft', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('contact_reveal_count', models.PositiveIntegerField(default=0)),
                ('bookmark_count', models.PositiveIntegerField(default=0)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('match_generation_version', models.PositiveIntegerField(default=1)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('search_document', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='kindness_wall.kindnesscategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kindness_listings', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kindness_reviewed_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آگهی دیوار مهربانی',
                'verbose_name_plural': 'آگهی\u200cهای دیوار مهربانی',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KindnessDuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('score', models.PositiveSmallIntegerField(validators=[apps.kindness_wall.validators.validate_match_score])),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('dismissed', 'نادیده\u200cگرفته\u200cشده'), ('confirmed', 'تأیید تکراری بودن')], default='active', max_length=20)),
                ('candidate_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_of_candidates', to='kindness_wall.kindnesslisting')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates', to='kindness_wall.kindnesslisting')),
            ],
        ),
        migrations.CreateModel(
            name='KindnessContactReveal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('phone_snapshot', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('listing_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kindness_received_contact_reveals', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kindness_contact_reveals', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_reveals', to='kindness_wall.kindnesslisting')),
            ],
        ),
        migrations.CreateModel(
            name='KindnessBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindness_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='kindness_wall.kindnesslisting')),
            ],
        ),
        migrations.CreateModel(
            name='KindnessListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ImageField(upload_to=apps.kindness_wall.models.listing_image_upload_path, validators=[apps.kindness_wall.validators.validate_listing_image_extension, apps.kindness_wall.validators.validate_listing_image_size])),
                ('caption', models.CharField(blank=True, max_length=260)),
                ('alt_text', models.CharField(blank=True, max_length=260)),
                ('image_kind', models.CharField(choices=[('cover', 'کاور'), ('gallery', 'گالری')], default='gallery', max_length=20)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('blur_hash', models.CharField(blank=True, max_length=120)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kindness_wall.kindnesslisting')),
            ],
            options={
                'verbose_name': 'تصویر آگهی دیوار مهربانی',
                'verbose_name_plural': 'تصاویر آگهی دیوار مهربانی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KindnessListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('reason', models.CharField(choices=[('spam', 'اسپم'), ('fraud', 'مشکوک به سوءاستفاده'), ('wrong_category', 'دسته\u200cبندی اشتباه'), ('inappropriate', 'محتوای نامناسب'), ('duplicate', 'تکراری'), ('expired', 'منقضی\u200cشده'), ('contact_invalid', 'شماره تماس نامعتبر'), ('other', 'سایر')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewed', 'بررسی\u200cشده'), ('rejected', 'رد گزارش')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='kindness_wall.kindnesslisting')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kindness_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kindness_reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KindnessMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('score', models.PositiveSmallIntegerField(validators=[apps.kindness_wall.validators.validate_match_score])),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('dismissed', 'نادیده\u200cگرفته\u200cشده'), ('contacted', 'تماس گرفته\u200cشده'), ('stale', 'قدیمی'), ('expired', 'منقضی\u200cشده')], db_index=True, default='active', max_length=20)),
                ('algorithm_version', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_matches', to='kindness_wall.kindnesslisting')),
                ('target_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_matches', to='kindness_wall.kindnesslisting')),
            ],
        ),
        migrations.CreateModel(
            name='KindnessListingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(choices=[('manual', 'دستی'), ('auto_title', 'استخراج از عنوان'), ('auto_description', 'استخراج از توضیحات'), ('admin', 'ادمین')], default='manual', max_length=30)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_tags', to='kindness_wall.kindnesslisting')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_tags', to='kindness_wall.kindnesstag')),
            ],
        ),
        migrations.AddIndex(
            model_name='kindnesscategory',
            index=models.Index(fields=['parent', 'is_active', 'order'], name='kindness_wa_parent__18bab9_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnesscategory',
            index=models.Index(fields=['path'], name='kindness_wa_path_f29c50_idx'),
        ),
        migrations.AddConstraint(
            model_name='kindnesscategory',
            constraint=models.UniqueConstraint(fields=('parent', 'title'), name='uniq_kindness_category_parent_title'),
        ),
        migrations.AddIndex(
            model_name='kindnesslisting',
            index=models.Index(fields=['status', 'listing_type', '-published_at'], name='kindness_wa_status_292d55_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnesslisting',
            index=models.Index(fields=['category', 'status', '-published_at'], name='kindness_wa_categor_6ae291_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnesslisting',
            index=models.Index(fields=['province', 'city', 'status'], name='kindness_wa_provinc_55bb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnesslisting',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='kindness_wa_owner_i_e183ec_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnesslisting',
            index=models.Index(fields=['expires_at'], name='kindness_wa_expires_b32114_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnessduplicatecandidate',
            index=models.Index(fields=['listing', 'status', '-score'], name='kindness_wa_listing_732fc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='kindnessduplicatecandidate',
            constraint=models.UniqueConstraint(fields=('listing', 'candidate_listing'), name='uniq_kindness_duplicate_candidate'),
        ),
        migrations.AddConstraint(
            model_name='kindnessduplicatecandidate',
            constraint=models.CheckConstraint(condition=models.Q(('listing', models.F('candidate_listing')), _negated=True), name='kindness_duplicate_not_self'),
        ),
        migrations.AddIndex(
            model_name='kindnesscontactreveal',
            index=models.Index(fields=['listing', '-created_at'], name='kindness_wa_listing_1b8f05_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnesscontactreveal',
            index=models.Index(fields=['viewer', '-created_at'], name='kindness_wa_viewer__a2d147_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnessbookmark',
            index=models.Index(fields=['user', '-created_at'], name='kindness_wa_user_id_378f75_idx'),
        ),
        migrations.AddConstraint(
            model_name='kindnessbookmark',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='uniq_kindness_bookmark'),
        ),
        migrations.AddIndex(
            model_name='kindnesslistingimage',
            index=models.Index(fields=['listing', 'is_cover', 'order'], name='kindness_wa_listing_ff07f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='kindnesslistingimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('listing',), name='uniq_kindness_listing_cover_image'),
        ),
        migrations.AddIndex(
            model_name='kindnesslistingreport',
            index=models.Index(fields=['status', '-created_at'], name='kindness_wa_status_189eec_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnesslistingreport',
            index=models.Index(fields=['listing', 'status'], name='kindness_wa_listing_c171a0_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnessmatch',
            index=models.Index(fields=['source_listing', 'status', '-score'], name='kindness_wa_source__500fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnessmatch',
            index=models.Index(fields=['target_listing', 'status', '-score'], name='kindness_wa_target__70ff2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='kindnessmatch',
            constraint=models.UniqueConstraint(fields=('source_listing', 'target_listing'), name='uniq_kindness_match_pair'),
        ),
        migrations.AddConstraint(
            model_name='kindnessmatch',
            constraint=models.CheckConstraint(condition=models.Q(('source_listing', models.F('target_listing')), _negated=True), name='kindness_match_not_self'),
        ),
        migrations.AddIndex(
            model_name='kindnesslistingtag',
            index=models.Index(fields=['tag', 'weight'], name='kindness_wa_tag_id_c79625_idx'),
        ),
        migrations.AddIndex(
            model_name='kindnesslistingtag',
            index=models.Index(fields=['listing', 'source'], name='kindness_wa_listing_c52540_idx'),
        ),
        migrations.AddConstraint(
            model_name='kindnesslistingtag',
            constraint=models.UniqueConstraint(fields=('listing', 'tag'), name='uniq_kindness_listing_tag'),
        ),
    ]
