# Generated by Django 6.0.6 on 2026-06-16 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindness_wall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KindnessRiskSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('signal_type', models.CharField(choices=[('contact_reveal_velocity', 'نمایش سریع شماره تماس'), ('listing_contact_spike', 'افزایش غیرعادی نمایش شماره آگهی'), ('duplicate_abuse', 'الگوی تکرار مشکوک')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('critical', 'بحرانی')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'باز'), ('reviewed', 'بررسی\u200cشده'), ('dismissed', 'ردشده')], db_index=True, default='open', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_signals', to='kindness_wall.kindnesslisting')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kindness_reviewed_risk_signals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kindness_risk_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سیگنال ریسک دیوار مهربانی',
                'verbose_name_plural': 'سیگنال\u200cهای ریسک دیوار مهربانی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['signal_type', 'status', '-created_at'], name='kindness_wa_signal__72c755_idx'), models.Index(fields=['user', 'status', '-created_at'], name='kindness_wa_user_id_c630c6_idx'), models.Index(fields=['listing', 'status', '-created_at'], name='kindness_wa_listing_d151ec_idx')],
            },
        ),
    ]
