# Generated by Django 6.0.6 on 2026-06-12 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('event_type', models.CharField(db_index=True, max_length=160)),
                ('app_label', models.CharField(db_index=True, max_length=80)),
                ('verb', models.CharField(choices=[('created', 'ایجاد کرد'), ('submitted', 'ارسال کرد'), ('updated', 'بروزرسانی کرد'), ('approved', 'تأیید شد'), ('rejected', 'رد شد'), ('replied', 'پاسخ دریافت کرد'), ('resolved', 'حل شد'), ('paid', 'پرداخت کرد'), ('issued', 'صادر شد'), ('revealed', 'مشاهده شد'), ('matched', 'تطبیق یافت'), ('notified', 'اعلان دریافت کرد')], default='notified', max_length=40)),
                ('title', models.CharField(max_length=260)),
                ('summary', models.TextField(blank=True)),
                ('aggregate_type', models.CharField(blank=True, max_length=120)),
                ('aggregate_id', models.CharField(blank=True, max_length=120)),
                ('visibility', models.CharField(choices=[('private', 'خصوصی'), ('admin', 'ادمین')], default='private', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رویداد فعالیت کاربر',
                'verbose_name_plural': 'رویدادهای فعالیت کاربران',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_us_user_id_b05f78_idx'), models.Index(fields=['event_type', '-created_at'], name='activity_us_event_t_b207c9_idx'), models.Index(fields=['app_label', '-created_at'], name='activity_us_app_lab_58c118_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='activity_us_aggrega_468fe6_idx')],
            },
        ),
    ]
