# Generated by Django 6.0.5 on 2026-05-13 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabyinContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('external_id', models.CharField(db_index=True, help_text='شناسه یکتای محتوا در سایت محتوانگار (مقدار id در JSON).', max_length=64, unique=True, verbose_name='شناسه منبع')),
                ('title', models.CharField(blank=True, default='', max_length=512, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('author_username', models.CharField(blank=True, default='', help_text='مقدار username از محتوانگار.', max_length=255, verbose_name='نام پدیدآورنده')),
                ('source_entity_id', models.PositiveIntegerField(default=0, verbose_name='entity_id منبع')),
                ('source_status', models.PositiveSmallIntegerField(default=0, verbose_name='وضعیت در منبع')),
                ('source_type', models.PositiveSmallIntegerField(default=0, verbose_name='نوع در منبع')),
                ('source_created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد در منبع')),
                ('source_updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ ویرایش در منبع')),
                ('source_url', models.URLField(blank=True, default='', max_length=512, verbose_name='لینک محتوا در محتوانگار')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='کل JSON دریافتی از منبع برای دیباگ و بازیابی.', verbose_name='داده خام JSON')),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 فیلدهای کلیدی برای تشخیص تغییر.', max_length=64, verbose_name='هش محتوا')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین همگام\u200cسازی')),
                ('is_deleted_in_source', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده در منبع')),
            ],
            options={
                'verbose_name': 'محتوای تبیین',
                'verbose_name_plural': 'محتواهای تبیین',
                'ordering': ['-source_created_at'],
                'indexes': [models.Index(fields=['is_active', 'is_deleted_in_source', '-source_created_at'], name='idx_tabyin_public_list'), models.Index(fields=['external_id'], name='idx_tabyin_external_id'), models.Index(fields=['-last_synced_at'], name='idx_tabyin_last_synced')],
            },
        ),
        migrations.CreateModel(
            name='TabyinAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('url', models.URLField(max_length=1024, verbose_name='آدرس کامل فایل')),
                ('relative_url', models.CharField(blank=True, default='', help_text='مقدار خام url از JSON منبع.', max_length=1024, verbose_name='آدرس نسبی فایل')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدئو'), ('audio', 'صوت'), ('other', 'سایر')], db_index=True, default='other', max_length=10, verbose_name='نوع رسانه')),
                ('size', models.CharField(blank=True, default='', help_text='مثلاً 1280X905', max_length=32, verbose_name='ابعاد')),
                ('duration', models.PositiveIntegerField(default=0, help_text='فقط برای ویدئو/صوت.', verbose_name='مدت (ثانیه)')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم فایل (KB)')),
                ('title', models.CharField(blank=True, default='', max_length=512, verbose_name='عنوان فایل')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tabyin.tabyincontent', verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'پیوست تبیین',
                'verbose_name_plural': 'پیوست\u200cهای تبیین',
                'ordering': ['order'],
            },
        ),
    ]
