# Generated by Django 6.0.5 on 2026-06-10 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabyin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tabyincontent',
            name='idx_tabyin_public_list',
        ),
        migrations.AddField(
            model_name='tabyincontent',
            name='admin_note',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت ادمین'),
        ),
        migrations.AddField(
            model_name='tabyincontent',
            name='origin',
            field=models.CharField(choices=[('external', 'همگام\u200cسازی خارجی'), ('user_submitted', 'ارسالی کاربر')], db_index=True, default='external', max_length=20, verbose_name='منشأ محتوا'),
        ),
        migrations.AddField(
            model_name='tabyincontent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی'),
        ),
        migrations.AddField(
            model_name='tabyincontent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabyin_reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده'),
        ),
        migrations.AddField(
            model_name='tabyincontent',
            name='submission_status',
            field=models.CharField(choices=[('approved', 'تأیید شده'), ('pending_review', 'در انتظار بررسی'), ('rejected', 'رد شده')], db_index=True, default='approved', max_length=20, verbose_name='وضعیت بررسی'),
        ),
        migrations.AddField(
            model_name='tabyincontent',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabyin_submissions', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='tabyincontent',
            name='external_id',
            field=models.CharField(db_index=True, help_text='برای محتوای خارجی id منبع و برای محتوای کاربر local UUID است.', max_length=64, unique=True, verbose_name='شناسه پایدار'),
        ),
        migrations.AddIndex(
            model_name='tabyincontent',
            index=models.Index(fields=['is_active', 'is_deleted_in_source', 'submission_status', '-source_created_at'], name='idx_tabyin_public_list'),
        ),
        migrations.AddIndex(
            model_name='tabyincontent',
            index=models.Index(fields=['origin', 'submission_status', '-created_at'], name='idx_tabyin_submission_queue'),
        ),
        migrations.AddIndex(
            model_name='tabyincontent',
            index=models.Index(fields=['submitted_by', 'submission_status', '-created_at'], name='idx_tabyin_user_submissions'),
        ),
    ]
