# Generated by Django 6.1 on 2026-08-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabyin', '0004_search_gin_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabyinattachment',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=127, verbose_name='نوع MIME فایل'),
        ),
        migrations.AddField(
            model_name='tabyinattachment',
            name='mirror_status',
            field=models.CharField(choices=[('none', 'بدون نیاز (محتوای منبع خارجی)'), ('pending', 'در انتظار آینه\u200cسازی'), ('mirrored', 'روی سرور بعثت'), ('failed', 'آینه\u200cسازی ناموفق')], db_index=True, default='none', max_length=10, verbose_name='وضعیت آینه\u200cسازی'),
        ),
        migrations.AddField(
            model_name='tabyinattachment',
            name='origin_url',
            field=models.URLField(blank=True, default='', help_text='برای پیوست\u200cهایی که اول با نشانی بیرونی ثبت و بعد روی سرور ما ذخیره شدند.', max_length=1024, verbose_name='نشانی اصلی پیش از آینه\u200cسازی'),
        ),
    ]
