# Generated by Django 6.0.5 on 2026-06-11 21:48

import apps.support_desk.models
import apps.support_desk.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=160, unique=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'تگ پشتیبانی',
                'verbose_name_plural': 'تگ\u200cهای پشتیبانی',
                'ordering': ['normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='SupportDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_default_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دپارتمان پشتیبانی',
                'verbose_name_plural': 'دپارتمان\u200cهای پشتیبانی',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('path', models.CharField(blank=True, db_index=True, max_length=700, unique=True)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tickets_count', models.PositiveIntegerField(default=0)),
                ('open_tickets_count', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='support_desk.supportcategory')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='support_desk.supportdepartment')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پشتیبانی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای پشتیبانی',
                'ordering': ['depth', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportCannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=180, unique=True)),
                ('body', models.TextField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canned_responses', to='support_desk.supportcategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canned_responses', to='support_desk.supportdepartment')),
            ],
            options={
                'verbose_name': 'پاسخ آماده پشتیبانی',
                'verbose_name_plural': 'پاسخ\u200cهای آماده پشتیبانی',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SupportSLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'معمولی'), ('high', 'زیاد'), ('urgent', 'فوری')], default='normal', max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'جزئی'), ('major', 'مهم'), ('critical', 'بحرانی'), ('blocker', 'مسدودکننده')], default='minor', max_length=20)),
                ('first_response_minutes', models.PositiveIntegerField(default=1440)),
                ('resolution_minutes', models.PositiveIntegerField(default=4320)),
                ('business_hours_only', models.BooleanField(default=False)),
                ('pause_when_waiting_for_user', models.BooleanField(default=True)),
                ('escalate_on_breach', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policies', to='support_desk.supportdepartment')),
            ],
            options={
                'verbose_name': 'سیاست SLA پشتیبانی',
                'verbose_name_plural': 'سیاست\u200cهای SLA پشتیبانی',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ticket_number', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('subject', models.CharField(max_length=260)),
                ('description_snapshot', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت\u200cشده'), ('open', 'باز'), ('in_progress', 'در حال بررسی'), ('waiting_for_user', 'منتظر پاسخ کاربر'), ('waiting_for_admin', 'منتظر پاسخ ادمین'), ('resolved', 'حل\u200cشده'), ('closed', 'بسته\u200cشده'), ('reopened', 'بازگشایی\u200cشده'), ('escalated', 'ارجاع/فوری\u200cشده'), ('spam', 'اسپم'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'معمولی'), ('high', 'زیاد'), ('urgent', 'فوری')], db_index=True, default='normal', max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'جزئی'), ('major', 'مهم'), ('critical', 'بحرانی'), ('blocker', 'مسدودکننده')], db_index=True, default='minor', max_length=20)),
                ('channel', models.CharField(choices=[('web', 'وب\u200cسایت'), ('admin', 'ادمین'), ('system', 'سیستم'), ('import', 'ورودی/ایمپورت')], default='web', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('first_admin_response_at', models.DateTimeField(blank=True, null=True)),
                ('last_user_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_admin_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('first_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('sla_breached_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sla_paused_at', models.DateTimeField(blank=True, null=True)),
                ('sla_total_paused_seconds', models.PositiveIntegerField(default=0)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('internal_note_count', models.PositiveIntegerField(default=0)),
                ('reopen_count', models.PositiveIntegerField(default=0)),
                ('satisfaction_rating_snapshot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('search_document', models.TextField(blank=True, default='')),
                ('applied_sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support_desk.supportslapolicy')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='support_desk.supportcategory')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='support_desk.supportdepartment')),
                ('escalated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportSLAEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('event_type', models.CharField(choices=[('policy_applied', 'اعمال SLA'), ('paused', 'توقف SLA'), ('resumed', 'ادامه SLA'), ('first_response_breached', 'نقض زمان اولین پاسخ'), ('resolution_breached', 'نقض زمان حل'), ('escalated', 'ارجاع به سطح بالاتر')], max_length=40)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_events', to='support_desk.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='SupportDuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('score', models.PositiveSmallIntegerField(validators=[apps.support_desk.validators.validate_duplicate_score])),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('dismissed', 'نادیده\u200cگرفته\u200cشده'), ('confirmed', 'تأیید تکراری بودن')], default='active', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_duplicate_reviews', to=settings.AUTH_USER_MODEL)),
                ('candidate_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_of_candidates', to='support_desk.supportticket')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates', to='support_desk.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('reason', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_assignments_to', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='support_desk.supportdepartment')),
                ('from_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_assignments_from', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='support_desk.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('message_type', models.CharField(choices=[('user_message', 'پیام کاربر'), ('admin_reply', 'پاسخ ادمین'), ('internal_note', 'یادداشت داخلی'), ('system_event', 'رویداد سیستمی'), ('status_change', 'تغییر وضعیت'), ('assignment_change', 'تغییر مسئول'), ('sla_event', 'رویداد SLA')], max_length=30)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('is_from_staff', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_desk.supportticket')),
            ],
            options={
                'verbose_name': 'پیام تیکت پشتیبانی',
                'verbose_name_plural': 'پیام\u200cهای تیکت پشتیبانی',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('file', models.FileField(upload_to=apps.support_desk.models.support_attachment_upload_path, validators=[apps.support_desk.validators.validate_attachment_extension, apps.support_desk.validators.validate_attachment_size])),
                ('original_filename', models.CharField(max_length=260)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('attachment_kind', models.CharField(choices=[('screenshot', 'اسکرین\u200cشات'), ('image', 'تصویر'), ('document', 'سند'), ('receipt', 'رسید'), ('other', 'سایر')], default='other', max_length=30)),
                ('visibility', models.CharField(choices=[('public', 'قابل مشاهده برای کاربر و ادمین'), ('internal_only', 'فقط داخلی')], default='public', max_length=30)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support_desk.supportticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_attachments', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support_desk.supportticketmessage')),
            ],
            options={
                'verbose_name': 'ضمیمه تیکت پشتیبانی',
                'verbose_name_plural': 'ضمیمه\u200cهای تیکت پشتیبانی',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction', to='support_desk.supportticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_satisfaction_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت\u200cشده'), ('open', 'باز'), ('in_progress', 'در حال بررسی'), ('waiting_for_user', 'منتظر پاسخ کاربر'), ('waiting_for_admin', 'منتظر پاسخ ادمین'), ('resolved', 'حل\u200cشده'), ('closed', 'بسته\u200cشده'), ('reopened', 'بازگشایی\u200cشده'), ('escalated', 'ارجاع/فوری\u200cشده'), ('spam', 'اسپم'), ('archived', 'آرشیوشده')], max_length=30)),
                ('to_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت\u200cشده'), ('open', 'باز'), ('in_progress', 'در حال بررسی'), ('waiting_for_user', 'منتظر پاسخ کاربر'), ('waiting_for_admin', 'منتظر پاسخ ادمین'), ('resolved', 'حل\u200cشده'), ('closed', 'بسته\u200cشده'), ('reopened', 'بازگشایی\u200cشده'), ('escalated', 'ارجاع/فوری\u200cشده'), ('spam', 'اسپم'), ('archived', 'آرشیوشده')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_status_changes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='support_desk.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('source', models.CharField(choices=[('user', 'کاربر'), ('admin', 'ادمین'), ('auto_triage', 'تریاژ هوشمند'), ('system', 'سیستم')], default='admin', max_length=30)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_tags', to='support_desk.supporttag')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to='support_desk.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_priority', models.CharField(choices=[('low', 'کم'), ('normal', 'معمولی'), ('high', 'زیاد'), ('urgent', 'فوری')], default='normal', max_length=20)),
                ('default_severity', models.CharField(choices=[('minor', 'جزئی'), ('major', 'مهم'), ('critical', 'بحرانی'), ('blocker', 'مسدودکننده')], default='minor', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_ticket_types', to='support_desk.supportcategory')),
                ('default_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_ticket_types', to='support_desk.supportdepartment')),
                ('default_sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_types', to='support_desk.supportslapolicy')),
            ],
            options={
                'verbose_name': 'نوع تیکت پشتیبانی',
                'verbose_name_plural': 'انواع تیکت پشتیبانی',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='support_desk.supporttickettype'),
        ),
        migrations.AddIndex(
            model_name='supportdepartment',
            index=models.Index(fields=['is_active', 'order'], name='support_des_is_acti_eab825_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcategory',
            index=models.Index(fields=['department', 'parent', 'is_active', 'order'], name='support_des_departm_2bbcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcategory',
            index=models.Index(fields=['path'], name='support_des_path_c74071_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'department', 'title'), name='uniq_support_category_parent_department_title'),
        ),
        migrations.AddIndex(
            model_name='supportcannedresponse',
            index=models.Index(fields=['department', 'category', 'is_active'], name='support_des_departm_b16d68_idx'),
        ),
        migrations.AddIndex(
            model_name='supportslapolicy',
            index=models.Index(fields=['department', 'priority', 'severity', 'is_active'], name='support_des_departm_875c16_idx'),
        ),
        migrations.AddIndex(
            model_name='supportslaevent',
            index=models.Index(fields=['ticket', 'occurred_at'], name='support_des_ticket__f10189_idx'),
        ),
        migrations.AddIndex(
            model_name='supportslaevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='support_des_event_t_b79b15_idx'),
        ),
        migrations.AddIndex(
            model_name='supportduplicatecandidate',
            index=models.Index(fields=['ticket', 'status', '-score'], name='support_des_ticket__6c5a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportduplicatecandidate',
            index=models.Index(fields=['status', '-created_at'], name='support_des_status_a8c526_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportduplicatecandidate',
            constraint=models.UniqueConstraint(fields=('ticket', 'candidate_ticket'), name='uniq_support_duplicate_candidate'),
        ),
        migrations.AddConstraint(
            model_name='supportduplicatecandidate',
            constraint=models.CheckConstraint(condition=models.Q(('ticket', models.F('candidate_ticket')), _negated=True), name='support_duplicate_not_self'),
        ),
        migrations.AddIndex(
            model_name='supportticketassignment',
            index=models.Index(fields=['ticket', '-created_at'], name='support_des_ticket__7ec3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketassignment',
            index=models.Index(fields=['assigned_to', '-created_at'], name='support_des_assigne_20e048_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_des_ticket__0dc556_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketmessage',
            index=models.Index(fields=['ticket', 'is_internal', 'created_at'], name='support_des_ticket__a1faa1_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketattachment',
            index=models.Index(fields=['ticket', 'visibility', 'created_at'], name='support_des_ticket__7810db_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketsatisfaction',
            index=models.Index(fields=['rating', '-created_at'], name='support_des_rating_f7af6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportticketsatisfaction',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='support_satisfaction_rating_1_5'),
        ),
        migrations.AddIndex(
            model_name='supportticketstatushistory',
            index=models.Index(fields=['ticket', '-created_at'], name='support_des_ticket__443bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketstatushistory',
            index=models.Index(fields=['to_status', '-created_at'], name='support_des_to_stat_02973a_idx'),
        ),
        migrations.AddIndex(
            model_name='supporttickettag',
            index=models.Index(fields=['tag', 'source'], name='support_des_tag_id_95f6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='supporttickettag',
            index=models.Index(fields=['ticket', 'source'], name='support_des_ticket__25198a_idx'),
        ),
        migrations.AddConstraint(
            model_name='supporttickettag',
            constraint=models.UniqueConstraint(fields=('ticket', 'tag'), name='uniq_support_ticket_tag'),
        ),
        migrations.AddIndex(
            model_name='supporttickettype',
            index=models.Index(fields=['is_active', 'order'], name='support_des_is_acti_40cc46_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['owner', 'status', '-last_activity_at'], name='support_des_owner_i_0eacda_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['department', 'status', 'priority', '-last_activity_at'], name='support_des_departm_464681_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status', '-last_activity_at'], name='support_des_assigne_5d68b4_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category', 'status'], name='support_des_categor_263eee_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticket_type', 'status'], name='support_des_ticket__db9079_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['first_response_due_at'], name='support_des_first_r_9ac33d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['resolution_due_at'], name='support_des_resolut_bf219c_idx'),
        ),
    ]
