# Generated by Django 6.0.5 on 2026-06-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_desk', '0002_seed_support_taxonomy'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supportcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('department', 'title'), name='uniq_support_root_category_department_title'),
        ),
    ]
