# Generated by Django 6.0.6 on 2026-06-16 12:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_desk', '0003_supportcategory_uniq_support_root_category_department_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportBusinessCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=180)),
                ('timezone_name', models.CharField(default='Asia/Tehran', max_length=80)),
                ('workday_start', models.TimeField(default=datetime.time(9, 0))),
                ('workday_end', models.TimeField(default=datetime.time(17, 0))),
                ('active_weekdays', models.JSONField(blank=True, default=list, help_text='0=Monday ... 6=Sunday')),
                ('is_default', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_calendars', to='support_desk.supportdepartment')),
            ],
            options={
                'verbose_name': 'تقویم کاری پشتیبانی',
                'verbose_name_plural': 'تقویم\u200cهای کاری پشتیبانی',
                'ordering': ['-is_default', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=180)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='support_desk.supportbusinesscalendar')),
            ],
            options={
                'verbose_name': 'تعطیلی پشتیبانی',
                'verbose_name_plural': 'تعطیلی\u200cهای پشتیبانی',
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='supportbusinesscalendar',
            index=models.Index(fields=['department', 'is_active', 'is_default'], name='support_des_departm_58827c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportholiday',
            index=models.Index(fields=['calendar', 'date'], name='support_des_calenda_d268e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportholiday',
            constraint=models.UniqueConstraint(fields=('calendar', 'date'), name='uniq_support_holiday_calendar_date'),
        ),
    ]
