# Generated by Django 6.0.6 on 2026-06-16 17:06

import apps.support_desk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_desk', '0004_supportbusinesscalendar_supportholiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportbusinesscalendar',
            name='workday_end',
            field=models.TimeField(default=apps.support_desk.models.default_workday_end),
        ),
        migrations.AlterField(
            model_name='supportbusinesscalendar',
            name='workday_start',
            field=models.TimeField(default=apps.support_desk.models.default_workday_start),
        ),
    ]
