# Generated by Django 6.0.6 on 2026-06-17 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_desk', '0005_alter_supportbusinesscalendar_workday_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportKnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=220, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=260, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیوشده')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_articles', to='support_desk.supportcategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_articles', to='support_desk.supportdepartment')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_articles', to='support_desk.supporttickettype')),
            ],
            options={
                'verbose_name': 'مقاله پایگاه دانش پشتیبانی',
                'verbose_name_plural': 'مقالات پایگاه دانش پشتیبانی',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SupportKnowledgeArticleUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('context', models.CharField(default='reply', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='support_desk.supportknowledgearticle')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_article_uses', to='support_desk.supportticket')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_knowledge_uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استفاده از مقاله پایگاه دانش',
                'verbose_name_plural': 'استفاده\u200cهای مقاله پایگاه دانش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportknowledgearticle',
            index=models.Index(fields=['status', 'is_active', '-published_at'], name='support_des_status_3789df_idx'),
        ),
        migrations.AddIndex(
            model_name='supportknowledgearticle',
            index=models.Index(fields=['department', 'category', 'status'], name='support_des_departm_17d828_idx'),
        ),
        migrations.AddIndex(
            model_name='supportknowledgearticle',
            index=models.Index(fields=['ticket_type', 'status'], name='support_des_ticket__a41614_idx'),
        ),
        migrations.AddIndex(
            model_name='supportknowledgearticleuse',
            index=models.Index(fields=['article', '-created_at'], name='support_des_article_e13425_idx'),
        ),
        migrations.AddIndex(
            model_name='supportknowledgearticleuse',
            index=models.Index(fields=['ticket', '-created_at'], name='support_des_ticket__7e2c2b_idx'),
        ),
    ]
