# Generated by Django 6.0.5 on 2026-05-12 17:57

import apps.public_reports.models
import apps.public_reports.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام گزارش\u200cدهنده')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='شماره تماس')),
                ('description', models.TextField(verbose_name='توضیحات گزارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewing', 'در حال بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت بررسی')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی گزارش\u200cدهنده')),
            ],
            options={
                'verbose_name': 'گزارش مردمی',
                'verbose_name_plural': 'گزارشات مردمی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='عنوان موضوع')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='شناسه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'موضوع گزارش',
                'verbose_name_plural': 'موضوعات گزارش',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ImageField(upload_to=apps.public_reports.models.report_attachment_upload_path, validators=[apps.public_reports.validators.validate_image_extension, apps.public_reports.validators.validate_image_size], verbose_name='تصویر مستند')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='public_reports.report', verbose_name='گزارش')),
            ],
            options={
                'verbose_name': 'تصویر مستند',
                'verbose_name_plural': 'تصاویر مستندات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='public_reports.reportsubject', verbose_name='موضوع گزارش'),
        ),
    ]
