# Generated by Django 6.0.5 on 2026-06-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='public_repo_status_6ac7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['subject', 'status', '-created_at'], name='public_repo_subject_b68181_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['submitter_ip', '-created_at'], name='public_repo_submitt_3fc983_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsubject',
            index=models.Index(fields=['is_active', 'order', 'title'], name='public_repo_is_acti_fab541_idx'),
        ),
    ]
