# Generated by Django 6.0.6 on 2026-06-18 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_add_certificate_gender_and_uniqueness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVideoProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('status', models.CharField(choices=[('queued', 'در صف'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل\u200cشده'), ('failed', 'ناموفق'), ('canceled', 'لغوشده')], db_index=True, default='queued', max_length=20)),
                ('provider', models.CharField(default='noop', max_length=50)),
                ('source_file_name', models.CharField(blank=True, max_length=500)),
                ('output_video_url', models.URLField(blank=True, max_length=1024)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_processing_jobs', to='lms.lesson')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_video_jobs_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job پردازش ویدئوی LMS',
                'verbose_name_plural': 'Jobهای پردازش ویدئوی LMS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lesson', 'status', '-created_at'], name='lms_video_job_lesson_status_idx'), models.Index(fields=['status', '-created_at'], name='lms_video_job_status_time_idx')],
            },
        ),
    ]
