# Generated by Django 6.0.6 on 2026-06-18 14:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_lessonvideoprocessingjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningActivityStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('statement_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('verb', models.CharField(choices=[('initialized', 'شروع شد'), ('progressed', 'پیشرفت کرد'), ('completed', 'تکمیل شد'), ('passed', 'قبول شد'), ('failed', 'مردود شد'), ('certificate_issued', 'مدرک صادر شد')], db_index=True, max_length=40)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=80)),
                ('actor_snapshot', models.JSONField(blank=True, default=dict)),
                ('object_snapshot', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lms_activity_statements', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_statements', to='lms.certificate')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_statements', to='lms.course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_statements', to='lms.enrollment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_statements', to='lms.lesson')),
                ('quiz_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_statements', to='lms.quizattempt')),
            ],
            options={
                'verbose_name': 'Learning activity statement',
                'verbose_name_plural': 'Learning activity statements',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['actor', 'verb', '-occurred_at'], name='lms_stmt_actor_verb_time_idx'), models.Index(fields=['course', 'verb', '-occurred_at'], name='lms_stmt_course_verb_time_idx'), models.Index(fields=['verb', '-occurred_at'], name='lms_stmt_verb_time_idx')],
            },
        ),
    ]
