# Generated by Django 6.1 on 2026-09-26 12:26

import apps.lms.models
import apps.lms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_search_gin_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='article_body',
            field=models.TextField(blank=True, verbose_name='متن جلسه'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'ویدئویی'), ('audio', 'صوتی'), ('document', 'سند/PDF'), ('article', 'متنی')], default='video', max_length=20, verbose_name='نوع محتوا'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.lms.models.lesson_document_upload_path, validators=[apps.lms.validators.validate_lesson_document_file], verbose_name='فایل سند جلسه'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='document_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان سند'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_required_for_certificate',
            field=models.BooleanField(default=True, verbose_name='الزامی برای صدور گواهی'),
        ),
    ]
