# Generated by Django 6.1 on 2026-10-02 16:11
#
# نکته‌ی استقرار: ایندکسِ رشته (parent, status, created_at) روی جدولِ روبه‌رشدِ
# پاسخ‌ها با «CREATE INDEX CONCURRENTLY» ساخته می‌شود تا نوشتن‌های زنده قفل
# نشوند (گیتِ migration-compat در update-back.sh). CONCURRENTLY داخلِ تراکنش
# اجرا نمی‌شود، برای همین کلِ مهاجرت atomic=False است؛ دو AddFieldِ nullable
# metadata-only و بلافصل هستند، پس غیراتمیک بودن بی‌خطر است. روی SQLite
# (توسعه و تست) که CONCURRENTLY ندارد، همان مسیرِ استاندارد‌ِ AddIndex کافی
# است و state در هر دو مسیر یکی می‌ماند (AddIndexConcurrently زیرکلاسِ
# AddIndex است).

import django.contrib.postgres.operations
import django.db.models.deletion
from django.conf import settings
from django.db import connection, migrations, models


def thread_index_operation():
    """عملیاتِ ایندکسِ رشته، هماهنگ با دیتابیسِ فعال (نگهبانِ state برابر)."""
    index = models.Index(fields=['parent', 'status', 'created_at'], name='lms_lessona_parent__0276ae_idx')
    if connection.vendor == 'postgresql':
        return django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='lessonanswer',
            index=index,
        )
    return migrations.AddIndex(model_name='lessonanswer', index=index)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('lms', '0006_lesson_content_type_document_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonanswer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='lms.lessonanswer', verbose_name='پاسخِ مادر (لنگرِ رشته)'),
        ),
        migrations.AddField(
            model_name='lessonanswer',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_by', to='lms.lessonanswer', verbose_name='در پاسخ به'),
        ),
        thread_index_operation(),
    ]
