# Generated by Django 6.1 on 2026-10-02 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_lesson_content_type_document_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonanswer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='lms.lessonanswer', verbose_name='پاسخِ مادر (لنگرِ رشته)'),
        ),
        migrations.AddField(
            model_name='lessonanswer',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_by', to='lms.lessonanswer', verbose_name='در پاسخ به'),
        ),
        migrations.AddIndex(
            model_name='lessonanswer',
            index=models.Index(fields=['parent', 'status', 'created_at'], name='lms_lessona_parent__0276ae_idx'),
        ),
    ]
