# Generated by Django 6.1.1 on 2026-10-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_lessonanswer_parent_lessonanswer_reply_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonanswer',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='media_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
