"""
Audit Log Action Constants.

تمام actionهای قابل ثبت در audit log به‌صورت constant تعریف می‌شوند
تا typo و inconsistency در سراسر پروژه جلوگیری شود.

هر بخش با یک header مشخص جدا شده و actionها alphabetical مرتب هستند.
"""

from __future__ import annotations

from typing import Final

# ── Authentication ──────────────────────────────────
LOGIN_SUCCESS: Final[str] = "LOGIN_SUCCESS"
LOGIN_FAILED: Final[str] = "LOGIN_FAILED"
LOGOUT: Final[str] = "LOGOUT"
SIGNUP_COMPLETED: Final[str] = "SIGNUP_COMPLETED"
PASSWORD_CHANGED: Final[str] = "PASSWORD_CHANGED"
PASSWORD_RESET_COMPLETED: Final[str] = "PASSWORD_RESET_COMPLETED"
IDENTIFIER_ADDED: Final[str] = "IDENTIFIER_ADDED"
IDENTIFIER_VERIFIED: Final[str] = "IDENTIFIER_VERIFIED"
PRIMARY_IDENTIFIER_CHANGED: Final[str] = "PRIMARY_IDENTIFIER_CHANGED"

# ── Admin actions ───────────────────────────────────
ADMIN_USER_UPDATED: Final[str] = "ADMIN_USER_UPDATED"
ADMIN_USER_DEACTIVATED: Final[str] = "ADMIN_USER_DEACTIVATED"
ADMIN_USER_ROLE_CHANGED: Final[str] = "ADMIN_USER_ROLE_CHANGED"

# ── Reports ─────────────────────────────────────────
REPORT_CREATED: Final[str] = "REPORT_CREATED"
REPORT_STATUS_CHANGED: Final[str] = "REPORT_STATUS_CHANGED"

# ── Report Subjects ─────────────────────────────────
SUBJECT_CREATED: Final[str] = "SUBJECT_CREATED"
SUBJECT_UPDATED: Final[str] = "SUBJECT_UPDATED"
SUBJECT_DELETED: Final[str] = "SUBJECT_DELETED"

# ── Tabyin ──────────────────────────────────────────
TABYIN_CONTENT_TOGGLED: Final[str] = "TABYIN_CONTENT_TOGGLED"
TABYIN_USER_SUBMISSION_APPROVED: Final[str] = "TABYIN_USER_SUBMISSION_APPROVED"
TABYIN_USER_SUBMISSION_REJECTED: Final[str] = "TABYIN_USER_SUBMISSION_REJECTED"
TABYIN_USER_SUBMISSION_SUBMITTED: Final[str] = "TABYIN_USER_SUBMISSION_SUBMITTED"
TABYIN_SYNC_DISPATCHED: Final[str] = "TABYIN_SYNC_DISPATCHED"
TABYIN_SYNC_FAILED: Final[str] = "TABYIN_SYNC_FAILED"
TABYIN_SYNC_STARTED: Final[str] = "TABYIN_SYNC_STARTED"
TABYIN_SYNC_SUCCEEDED: Final[str] = "TABYIN_SYNC_SUCCEEDED"

# ── R4J — Reward for Justice ────────────────────────
R4J_CRIMINAL_CREATED: Final[str] = "R4J_CRIMINAL_CREATED"
R4J_CRIMINAL_UPDATED: Final[str] = "R4J_CRIMINAL_UPDATED"
R4J_CRIMINAL_PUBLISHED: Final[str] = "R4J_CRIMINAL_PUBLISHED"
R4J_CRIMINAL_UNPUBLISHED: Final[str] = "R4J_CRIMINAL_UNPUBLISHED"
R4J_CRIMINAL_DELETED: Final[str] = "R4J_CRIMINAL_DELETED"

R4J_CRIMINAL_PHOTO_ADDED: Final[str] = "R4J_CRIMINAL_PHOTO_ADDED"
R4J_CRIMINAL_PHOTO_REMOVED: Final[str] = "R4J_CRIMINAL_PHOTO_REMOVED"
R4J_CRIMINAL_PHONE_ADDED: Final[str] = "R4J_CRIMINAL_PHONE_ADDED"
R4J_CRIMINAL_PHONE_REMOVED: Final[str] = "R4J_CRIMINAL_PHONE_REMOVED"
R4J_CRIMINAL_SOCIAL_ADDED: Final[str] = "R4J_CRIMINAL_SOCIAL_ADDED"
R4J_CRIMINAL_SOCIAL_REMOVED: Final[str] = "R4J_CRIMINAL_SOCIAL_REMOVED"
R4J_CRIMINAL_VISIBILITY_CHANGED: Final[str] = "R4J_CRIMINAL_VISIBILITY_CHANGED"

R4J_REPORT_SUBMITTED: Final[str] = "R4J_REPORT_SUBMITTED"
R4J_REPORT_REVIEWED: Final[str] = "R4J_REPORT_REVIEWED"
R4J_REPORT_CANCEL_REQUESTED: Final[str] = "R4J_REPORT_CANCEL_REQUESTED"
R4J_REPORT_CANCEL_APPROVED: Final[str] = "R4J_REPORT_CANCEL_APPROVED"
R4J_REPORT_CANCEL_REJECTED: Final[str] = "R4J_REPORT_CANCEL_REJECTED"

R4J_BOUNTY_CREATED: Final[str] = "R4J_BOUNTY_CREATED"
R4J_BOUNTY_UPDATED: Final[str] = "R4J_BOUNTY_UPDATED"
R4J_BOUNTY_CANCEL_REQUESTED: Final[str] = "R4J_BOUNTY_CANCEL_REQUESTED"
R4J_BOUNTY_CANCEL_APPROVED: Final[str] = "R4J_BOUNTY_CANCEL_APPROVED"
R4J_BOUNTY_CANCEL_REJECTED: Final[str] = "R4J_BOUNTY_CANCEL_REJECTED"
R4J_BOUNTY_FORCE_DELETED: Final[str] = "R4J_BOUNTY_FORCE_DELETED"

# ── Madadkar — Charitable Crowdfunding ──────────────
# Sponsor management
MADADKAR_SPONSOR_CREATED: Final[str] = "MADADKAR_SPONSOR_CREATED"
MADADKAR_SPONSOR_UPDATED: Final[str] = "MADADKAR_SPONSOR_UPDATED"
MADADKAR_SPONSOR_DELETED: Final[str] = "MADADKAR_SPONSOR_DELETED"

# Campaign lifecycle
MADADKAR_CAMPAIGN_CREATED: Final[str] = "MADADKAR_CAMPAIGN_CREATED"
MADADKAR_CAMPAIGN_UPDATED: Final[str] = "MADADKAR_CAMPAIGN_UPDATED"
MADADKAR_CAMPAIGN_PUBLISHED: Final[str] = "MADADKAR_CAMPAIGN_PUBLISHED"
MADADKAR_CAMPAIGN_CLOSED: Final[str] = "MADADKAR_CAMPAIGN_CLOSED"
MADADKAR_CAMPAIGN_AUTO_COMPLETED: Final[str] = "MADADKAR_CAMPAIGN_AUTO_COMPLETED"
MADADKAR_CAMPAIGN_DELETED: Final[str] = "MADADKAR_CAMPAIGN_DELETED"

# Campaign gallery
MADADKAR_CAMPAIGN_IMAGE_ADDED: Final[str] = "MADADKAR_CAMPAIGN_IMAGE_ADDED"
MADADKAR_CAMPAIGN_IMAGE_REMOVED: Final[str] = "MADADKAR_CAMPAIGN_IMAGE_REMOVED"

# Participation & Payment
MADADKAR_PARTICIPATION_INITIATED: Final[str] = "MADADKAR_PARTICIPATION_INITIATED"
MADADKAR_PARTICIPATION_EXPIRED: Final[str] = "MADADKAR_PARTICIPATION_EXPIRED"
MADADKAR_PAYMENT_SUCCESS: Final[str] = "MADADKAR_PAYMENT_SUCCESS"
MADADKAR_PAYMENT_FAILED: Final[str] = "MADADKAR_PAYMENT_FAILED"

# Admin analytics
MADADKAR_EXPORT_PARTICIPANTS: Final[str] = "MADADKAR_EXPORT_PARTICIPANTS"
