"""
Audit Log Action Constants.

تمام actionهای قابل ثبت در audit log به‌صورت constant تعریف می‌شوند
تا typo و inconsistency در سراسر پروژه جلوگیری شود.

هر بخش با یک header مشخص جدا شده و actionها alphabetical مرتب هستند.
"""

from __future__ import annotations

from typing import Final

# ── Authentication ──────────────────────────────────
LOGIN_SUCCESS: Final[str] = "LOGIN_SUCCESS"
LOGIN_FAILED: Final[str] = "LOGIN_FAILED"
LOGOUT: Final[str] = "LOGOUT"
SIGNUP_COMPLETED: Final[str] = "SIGNUP_COMPLETED"
PASSWORD_CHANGED: Final[str] = "PASSWORD_CHANGED"
PASSWORD_RESET_COMPLETED: Final[str] = "PASSWORD_RESET_COMPLETED"
IDENTIFIER_ADDED: Final[str] = "IDENTIFIER_ADDED"
IDENTIFIER_VERIFIED: Final[str] = "IDENTIFIER_VERIFIED"
PRIMARY_IDENTIFIER_CHANGED: Final[str] = "PRIMARY_IDENTIFIER_CHANGED"

# ── Admin actions ───────────────────────────────────
ADMIN_USER_UPDATED: Final[str] = "ADMIN_USER_UPDATED"
ADMIN_USER_DEACTIVATED: Final[str] = "ADMIN_USER_DEACTIVATED"
ADMIN_USER_ROLE_CHANGED: Final[str] = "ADMIN_USER_ROLE_CHANGED"

# ── Audit Logs / Forensics ──────────────────────────
AUDIT_PACKAGE_EXPORTED: Final[str] = "AUDIT_PACKAGE_EXPORTED"

# ── Reports ─────────────────────────────────────────
REPORT_CREATED: Final[str] = "REPORT_CREATED"
REPORT_STATUS_CHANGED: Final[str] = "REPORT_STATUS_CHANGED"

# ── Report Subjects ─────────────────────────────────
SUBJECT_CREATED: Final[str] = "SUBJECT_CREATED"
SUBJECT_UPDATED: Final[str] = "SUBJECT_UPDATED"
SUBJECT_DELETED: Final[str] = "SUBJECT_DELETED"

# ── Tabyin ──────────────────────────────────────────
TABYIN_CONTENT_TOGGLED: Final[str] = "TABYIN_CONTENT_TOGGLED"
TABYIN_USER_SUBMISSION_APPROVED: Final[str] = "TABYIN_USER_SUBMISSION_APPROVED"
TABYIN_USER_SUBMISSION_REJECTED: Final[str] = "TABYIN_USER_SUBMISSION_REJECTED"
TABYIN_USER_SUBMISSION_SUBMITTED: Final[str] = "TABYIN_USER_SUBMISSION_SUBMITTED"
TABYIN_SYNC_DISPATCHED: Final[str] = "TABYIN_SYNC_DISPATCHED"
TABYIN_SYNC_FAILED: Final[str] = "TABYIN_SYNC_FAILED"
TABYIN_SYNC_STARTED: Final[str] = "TABYIN_SYNC_STARTED"
TABYIN_SYNC_SUCCEEDED: Final[str] = "TABYIN_SYNC_SUCCEEDED"

# ── R4J — Reward for Justice ────────────────────────
R4J_CRIMINAL_CREATED: Final[str] = "R4J_CRIMINAL_CREATED"
R4J_CRIMINAL_UPDATED: Final[str] = "R4J_CRIMINAL_UPDATED"
R4J_CRIMINAL_PUBLISHED: Final[str] = "R4J_CRIMINAL_PUBLISHED"
R4J_CRIMINAL_UNPUBLISHED: Final[str] = "R4J_CRIMINAL_UNPUBLISHED"
R4J_CRIMINAL_DELETED: Final[str] = "R4J_CRIMINAL_DELETED"

R4J_CRIMINAL_PHOTO_ADDED: Final[str] = "R4J_CRIMINAL_PHOTO_ADDED"
R4J_CRIMINAL_PHOTO_REMOVED: Final[str] = "R4J_CRIMINAL_PHOTO_REMOVED"
R4J_CRIMINAL_PHONE_ADDED: Final[str] = "R4J_CRIMINAL_PHONE_ADDED"
R4J_CRIMINAL_PHONE_REMOVED: Final[str] = "R4J_CRIMINAL_PHONE_REMOVED"
R4J_CRIMINAL_SOCIAL_ADDED: Final[str] = "R4J_CRIMINAL_SOCIAL_ADDED"
R4J_CRIMINAL_SOCIAL_REMOVED: Final[str] = "R4J_CRIMINAL_SOCIAL_REMOVED"
R4J_CRIMINAL_VISIBILITY_CHANGED: Final[str] = "R4J_CRIMINAL_VISIBILITY_CHANGED"

R4J_REPORT_SUBMITTED: Final[str] = "R4J_REPORT_SUBMITTED"
R4J_REPORT_REVIEWED: Final[str] = "R4J_REPORT_REVIEWED"
R4J_REPORT_CANCEL_REQUESTED: Final[str] = "R4J_REPORT_CANCEL_REQUESTED"
R4J_REPORT_CANCEL_APPROVED: Final[str] = "R4J_REPORT_CANCEL_APPROVED"
R4J_REPORT_CANCEL_REJECTED: Final[str] = "R4J_REPORT_CANCEL_REJECTED"

R4J_BOUNTY_CREATED: Final[str] = "R4J_BOUNTY_CREATED"
R4J_BOUNTY_UPDATED: Final[str] = "R4J_BOUNTY_UPDATED"
R4J_BOUNTY_CANCEL_REQUESTED: Final[str] = "R4J_BOUNTY_CANCEL_REQUESTED"
R4J_BOUNTY_CANCEL_APPROVED: Final[str] = "R4J_BOUNTY_CANCEL_APPROVED"
R4J_BOUNTY_CANCEL_REJECTED: Final[str] = "R4J_BOUNTY_CANCEL_REJECTED"
R4J_BOUNTY_FORCE_DELETED: Final[str] = "R4J_BOUNTY_FORCE_DELETED"

# ── Kindness Wall — Divar-e Mehrabani ──────────────
KINDNESS_CATEGORY_CREATED: Final[str] = "KINDNESS_CATEGORY_CREATED"
KINDNESS_CATEGORY_UPDATED: Final[str] = "KINDNESS_CATEGORY_UPDATED"
KINDNESS_CATEGORY_DELETED: Final[str] = "KINDNESS_CATEGORY_DELETED"
KINDNESS_LISTING_APPROVED: Final[str] = "KINDNESS_LISTING_APPROVED"
KINDNESS_LISTING_CLOSED: Final[str] = "KINDNESS_LISTING_CLOSED"
KINDNESS_LISTING_CREATED: Final[str] = "KINDNESS_LISTING_CREATED"
KINDNESS_LISTING_DELETED: Final[str] = "KINDNESS_LISTING_DELETED"
KINDNESS_LISTING_REJECTED: Final[str] = "KINDNESS_LISTING_REJECTED"
KINDNESS_LISTING_REPORTED: Final[str] = "KINDNESS_LISTING_REPORTED"
KINDNESS_LISTING_SUBMITTED: Final[str] = "KINDNESS_LISTING_SUBMITTED"
KINDNESS_LISTING_SUSPENDED: Final[str] = "KINDNESS_LISTING_SUSPENDED"
KINDNESS_LISTING_UPDATED: Final[str] = "KINDNESS_LISTING_UPDATED"
KINDNESS_MATCH_GENERATED: Final[str] = "KINDNESS_MATCH_GENERATED"
KINDNESS_CONTACT_REVEALED: Final[str] = "KINDNESS_CONTACT_REVEALED"
KINDNESS_REPORT_REVIEWED: Final[str] = "KINDNESS_REPORT_REVIEWED"
KINDNESS_BOOKMARK_CREATED: Final[str] = "KINDNESS_BOOKMARK_CREATED"
KINDNESS_BOOKMARK_DELETED: Final[str] = "KINDNESS_BOOKMARK_DELETED"
KINDNESS_DUPLICATE_REVIEWED: Final[str] = "KINDNESS_DUPLICATE_REVIEWED"
KINDNESS_LISTINGS_EXPORTED: Final[str] = "KINDNESS_LISTINGS_EXPORTED"
KINDNESS_REPORTS_EXPORTED: Final[str] = "KINDNESS_REPORTS_EXPORTED"

# ── Support Desk — Ticketing ─────────────────────────
SUPPORT_DEPARTMENT_CREATED: Final[str] = "SUPPORT_DEPARTMENT_CREATED"
SUPPORT_DEPARTMENT_UPDATED: Final[str] = "SUPPORT_DEPARTMENT_UPDATED"
SUPPORT_DEPARTMENT_DEACTIVATED: Final[str] = "SUPPORT_DEPARTMENT_DEACTIVATED"
SUPPORT_CATEGORY_CREATED: Final[str] = "SUPPORT_CATEGORY_CREATED"
SUPPORT_CATEGORY_UPDATED: Final[str] = "SUPPORT_CATEGORY_UPDATED"
SUPPORT_CATEGORY_DEACTIVATED: Final[str] = "SUPPORT_CATEGORY_DEACTIVATED"
SUPPORT_TICKET_TYPE_CREATED: Final[str] = "SUPPORT_TICKET_TYPE_CREATED"
SUPPORT_TICKET_TYPE_UPDATED: Final[str] = "SUPPORT_TICKET_TYPE_UPDATED"
SUPPORT_SLA_POLICY_CREATED: Final[str] = "SUPPORT_SLA_POLICY_CREATED"
SUPPORT_SLA_POLICY_UPDATED: Final[str] = "SUPPORT_SLA_POLICY_UPDATED"
SUPPORT_TICKET_CREATED: Final[str] = "SUPPORT_TICKET_CREATED"
SUPPORT_TICKET_SUBMITTED: Final[str] = "SUPPORT_TICKET_SUBMITTED"
SUPPORT_TICKET_UPDATED: Final[str] = "SUPPORT_TICKET_UPDATED"
SUPPORT_TICKET_ASSIGNED: Final[str] = "SUPPORT_TICKET_ASSIGNED"
SUPPORT_TICKET_REPLIED: Final[str] = "SUPPORT_TICKET_REPLIED"
SUPPORT_TICKET_INTERNAL_NOTE_ADDED: Final[str] = "SUPPORT_TICKET_INTERNAL_NOTE_ADDED"
SUPPORT_TICKET_STATUS_CHANGED: Final[str] = "SUPPORT_TICKET_STATUS_CHANGED"
SUPPORT_TICKET_RESOLVED: Final[str] = "SUPPORT_TICKET_RESOLVED"
SUPPORT_TICKET_CLOSED: Final[str] = "SUPPORT_TICKET_CLOSED"
SUPPORT_TICKET_REOPENED: Final[str] = "SUPPORT_TICKET_REOPENED"
SUPPORT_TICKET_ESCALATED: Final[str] = "SUPPORT_TICKET_ESCALATED"
SUPPORT_ATTACHMENT_ADDED: Final[str] = "SUPPORT_ATTACHMENT_ADDED"
SUPPORT_SATISFACTION_SUBMITTED: Final[str] = "SUPPORT_SATISFACTION_SUBMITTED"
SUPPORT_CANNED_RESPONSE_CREATED: Final[str] = "SUPPORT_CANNED_RESPONSE_CREATED"
SUPPORT_CANNED_RESPONSE_USED: Final[str] = "SUPPORT_CANNED_RESPONSE_USED"
SUPPORT_EXPORT_GENERATED: Final[str] = "SUPPORT_EXPORT_GENERATED"
SUPPORT_DUPLICATE_REVIEWED: Final[str] = "SUPPORT_DUPLICATE_REVIEWED"
SUPPORT_SLA_BREACHED: Final[str] = "SUPPORT_SLA_BREACHED"

# ── LMS — Learning Management System ─────────────────
LMS_CATEGORY_CREATED: Final[str] = "LMS_CATEGORY_CREATED"
LMS_COURSE_CREATED: Final[str] = "LMS_COURSE_CREATED"
LMS_COURSE_PUBLISHED: Final[str] = "LMS_COURSE_PUBLISHED"
LMS_COURSE_ARCHIVED: Final[str] = "LMS_COURSE_ARCHIVED"
LMS_LESSON_CREATED: Final[str] = "LMS_LESSON_CREATED"
LMS_LESSON_MEDIA_ACCESSED: Final[str] = "LMS_LESSON_MEDIA_ACCESSED"
LMS_ENROLLMENT_CREATED: Final[str] = "LMS_ENROLLMENT_CREATED"
LMS_COURSE_REPORT_EXPORTED: Final[str] = "LMS_COURSE_REPORT_EXPORTED"
LMS_PROGRESS_UPDATED: Final[str] = "LMS_PROGRESS_UPDATED"
LMS_QUESTION_CREATED: Final[str] = "LMS_QUESTION_CREATED"
LMS_ANSWER_CREATED: Final[str] = "LMS_ANSWER_CREATED"
LMS_DISCUSSION_REPORTED: Final[str] = "LMS_DISCUSSION_REPORTED"
LMS_QUIZ_CREATED: Final[str] = "LMS_QUIZ_CREATED"
LMS_QUIZ_PUBLISHED: Final[str] = "LMS_QUIZ_PUBLISHED"
LMS_QUIZ_ATTEMPT_STARTED: Final[str] = "LMS_QUIZ_ATTEMPT_STARTED"
LMS_QUIZ_ATTEMPT_SUBMITTED: Final[str] = "LMS_QUIZ_ATTEMPT_SUBMITTED"
LMS_QUIZ_ATTEMPT_PASSED: Final[str] = "LMS_QUIZ_ATTEMPT_PASSED"
LMS_QUIZ_ATTEMPT_FAILED: Final[str] = "LMS_QUIZ_ATTEMPT_FAILED"
LMS_QUIZ_UNLOCKED: Final[str] = "LMS_QUIZ_UNLOCKED"
LMS_CERTIFICATE_ISSUED: Final[str] = "LMS_CERTIFICATE_ISSUED"
LMS_CERTIFICATE_REVOKED: Final[str] = "LMS_CERTIFICATE_REVOKED"

# ── Madadkar — Charitable Crowdfunding ──────────────
# Sponsor management
MADADKAR_SPONSOR_CREATED: Final[str] = "MADADKAR_SPONSOR_CREATED"
MADADKAR_SPONSOR_UPDATED: Final[str] = "MADADKAR_SPONSOR_UPDATED"
MADADKAR_SPONSOR_DELETED: Final[str] = "MADADKAR_SPONSOR_DELETED"

# Campaign lifecycle
MADADKAR_CAMPAIGN_CREATED: Final[str] = "MADADKAR_CAMPAIGN_CREATED"
MADADKAR_CAMPAIGN_UPDATED: Final[str] = "MADADKAR_CAMPAIGN_UPDATED"
MADADKAR_CAMPAIGN_PUBLISHED: Final[str] = "MADADKAR_CAMPAIGN_PUBLISHED"
MADADKAR_CAMPAIGN_CLOSED: Final[str] = "MADADKAR_CAMPAIGN_CLOSED"
MADADKAR_CAMPAIGN_AUTO_COMPLETED: Final[str] = "MADADKAR_CAMPAIGN_AUTO_COMPLETED"
MADADKAR_CAMPAIGN_DELETED: Final[str] = "MADADKAR_CAMPAIGN_DELETED"

# Campaign gallery
MADADKAR_CAMPAIGN_IMAGE_ADDED: Final[str] = "MADADKAR_CAMPAIGN_IMAGE_ADDED"
MADADKAR_CAMPAIGN_IMAGE_REMOVED: Final[str] = "MADADKAR_CAMPAIGN_IMAGE_REMOVED"

# Participation & Payment
MADADKAR_PARTICIPATION_INITIATED: Final[str] = "MADADKAR_PARTICIPATION_INITIATED"
MADADKAR_PARTICIPATION_EXPIRED: Final[str] = "MADADKAR_PARTICIPATION_EXPIRED"
MADADKAR_PAYMENT_SUCCESS: Final[str] = "MADADKAR_PAYMENT_SUCCESS"
MADADKAR_PAYMENT_FAILED: Final[str] = "MADADKAR_PAYMENT_FAILED"

# Refunds / adjustments
MADADKAR_REFUND_REQUESTED: Final[str] = "MADADKAR_REFUND_REQUESTED"
MADADKAR_REFUND_APPROVED: Final[str] = "MADADKAR_REFUND_APPROVED"
MADADKAR_REFUND_REJECTED: Final[str] = "MADADKAR_REFUND_REJECTED"
MADADKAR_REFUND_COMPLETED: Final[str] = "MADADKAR_REFUND_COMPLETED"
MADADKAR_ADJUSTMENT_CREATED: Final[str] = "MADADKAR_ADJUSTMENT_CREATED"
MADADKAR_ADJUSTMENT_APPROVED: Final[str] = "MADADKAR_ADJUSTMENT_APPROVED"
MADADKAR_ADJUSTMENT_REJECTED: Final[str] = "MADADKAR_ADJUSTMENT_REJECTED"
MADADKAR_ADJUSTMENT_APPLIED: Final[str] = "MADADKAR_ADJUSTMENT_APPLIED"
MADADKAR_RISK_SIGNAL_REVIEWED: Final[str] = "MADADKAR_RISK_SIGNAL_REVIEWED"
MADADKAR_RECEIPT_ACCESSED: Final[str] = "MADADKAR_RECEIPT_ACCESSED"
MADADKAR_RECEIPT_VERIFIED: Final[str] = "MADADKAR_RECEIPT_VERIFIED"
MADADKAR_RECEIPT_RESENT: Final[str] = "MADADKAR_RECEIPT_RESENT"
MADADKAR_RECONCILIATION_IMPORTED: Final[str] = "MADADKAR_RECONCILIATION_IMPORTED"
MADADKAR_RECONCILIATION_EXPORTED: Final[str] = "MADADKAR_RECONCILIATION_EXPORTED"

# Admin analytics
MADADKAR_EXPORT_PARTICIPANTS: Final[str] = "MADADKAR_EXPORT_PARTICIPANTS"
