# Generated by Django 6.0.5 on 2026-05-27 22:07

import apps.madadkar.models
import apps.madadkar.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان حرکت')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='در صورت خالی بودن، از روی عنوان به\u200cصورت خودکار ساخته می\u200cشود.', max_length=320, unique=True, verbose_name='شناسه URL')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('cover_image', models.ImageField(upload_to=apps.madadkar.models.campaign_cover_upload_path, validators=[apps.madadkar.validators.validate_image_extension, apps.madadkar.validators.validate_image_size], verbose_name='تصویر اصلی')),
                ('total_amount', models.PositiveBigIntegerField(validators=[apps.madadkar.validators.validate_total_amount], verbose_name='مبلغ کل (تومان)')),
                ('total_shares', models.PositiveIntegerField(validators=[apps.madadkar.validators.validate_total_shares], verbose_name='تعداد کل سهم')),
                ('share_price', models.PositiveBigIntegerField(help_text='به\u200cصورت خودکار از total_amount / total_shares محاسبه می\u200cشود.', verbose_name='قیمت هر سهم (تومان)')),
                ('purchased_shares', models.PositiveIntegerField(default=0, help_text='مجموع سهم\u200cهای PAID + PENDING_PAYMENT.', verbose_name='سهم\u200cهای فروخته/رزرو شده')),
                ('purchased_amount', models.PositiveBigIntegerField(default=0, help_text='فقط مجموع مبلغ پرداخت\u200cهای قطعی (PAID).', verbose_name='مبلغ جمع\u200cآوری\u200cشده (تومان)')),
                ('participant_count', models.PositiveIntegerField(default=0, verbose_name='تعداد مشارکت\u200cکنندگان یکتا')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('completed', 'تکمیل\u200cشده'), ('closed', 'بسته\u200cشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_visible', models.BooleanField(db_index=True, default=False, help_text='در صورت غیرفعال بودن، حرکت در API عمومی نمایش داده نمی\u200cشود.', verbose_name='قابل نمایش در سایت')),
                ('has_deadline', models.BooleanField(default=False, verbose_name='دارای مهلت زمانی')),
                ('deadline', models.DateTimeField(blank=True, help_text='فقط زمانی استفاده می\u200cشود که has_deadline=True باشد.', null=True, verbose_name='مهلت پایان')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل (۱۰۰٪ فروش)')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بسته شدن')),
            ],
            options={
                'verbose_name': 'حرکت',
                'verbose_name_plural': 'حرکت\u200cها',
                'ordering': ['-published_at', '-created_at'],
            },
            managers=[
                ('visible', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('share_count', models.PositiveIntegerField(validators=[apps.madadkar.validators.validate_share_count], verbose_name='تعداد سهم')),
                ('share_price_snapshot', models.PositiveBigIntegerField(verbose_name='قیمت سهم در لحظه خرید (تومان)')),
                ('total_amount', models.PositiveBigIntegerField(verbose_name='مبلغ کل (تومان)')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق'), ('expired', 'منقضی\u200cشده')], db_index=True, default='pending_payment', max_length=20, verbose_name='وضعیت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت موفق')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='madadkar.campaign', verbose_name='حرکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madadkar_participations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مشارکت',
                'verbose_name_plural': 'مشارکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (تومان)')),
                ('gateway_name', models.CharField(help_text='مثال: sandbox, zarinpal, idpay', max_length=50, verbose_name='نام درگاه')),
                ('authority', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='کد رهگیری درگاه (authority)')),
                ('ref_id', models.CharField(blank=True, help_text='پس از verify موفق توسط درگاه برگردانده می\u200cشود.', max_length=100, verbose_name='شناسه مرجع پرداخت (ref_id)')),
                ('gateway_status', models.CharField(blank=True, max_length=50, verbose_name='کد وضعیت خام درگاه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید توسط درگاه')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='madadkar.participation', verbose_name='مشارکت')),
                ('user', models.ForeignKey(help_text='denormalized برای سرعت query (برابر participation.user).', on_delete=django.db.models.deletion.PROTECT, related_name='madadkar_payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام مددکار')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='در صورت خالی بودن، از روی نام به\u200cصورت خودکار ساخته می\u200cشود.', max_length=220, unique=True, verbose_name='شناسه URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.madadkar.models.sponsor_logo_upload_path, validators=[apps.madadkar.validators.validate_image_extension, apps.madadkar.validators.validate_image_size], verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'مددکار',
                'verbose_name_plural': 'مددکاران',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='madadkar_sponsor_slug_idx')],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='madadkar.sponsor', verbose_name='مددکار'),
        ),
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ImageField(upload_to=apps.madadkar.models.campaign_gallery_upload_path, validators=[apps.madadkar.validators.validate_image_extension, apps.madadkar.validators.validate_image_size], verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='madadkar.campaign', verbose_name='حرکت')),
            ],
            options={
                'verbose_name': 'تصویر گالری حرکت',
                'verbose_name_plural': 'تصاویر گالری حرکت\u200cها',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['campaign', 'display_order'], name='madadkar_img_camp_order_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['campaign', 'status'], name='madadkar_part_camp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['user', 'status'], name='madadkar_part_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['status', 'created_at'], name='madadkar_part_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.CheckConstraint(condition=models.Q(('share_count__gte', 1)), name='madadkar_part_share_count_min'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.CheckConstraint(condition=models.Q(('share_price_snapshot__gte', 1)), name='madadkar_part_price_snapshot_min'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 1)), name='madadkar_part_total_amount_min'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['authority'], name='madadkar_pay_auth_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='madadkar_pay_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='madadkar_pay_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='madadkar_pay_amount_min'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['slug'], name='madadkar_camp_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'is_visible'], name='madadkar_camp_status_vis_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['sponsor', 'status'], name='madadkar_camp_sponsor_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['deadline'], name='madadkar_camp_deadline_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 1000)), name='madadkar_camp_total_amount_min'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('total_shares__gte', 1)), name='madadkar_camp_total_shares_min'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('share_price__gte', 1)), name='madadkar_camp_share_price_min'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('purchased_shares__lte', models.F('total_shares'))), name='madadkar_camp_purchased_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deadline__isnull', True), ('has_deadline', False)), models.Q(('deadline__isnull', False), ('has_deadline', True)), _connector='OR'), name='madadkar_camp_deadline_consistency'),
        ),
    ]
