# Generated by Django 6.0.5 on 2026-06-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadkar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('event_kind', models.CharField(choices=[('created', 'ایجاد پرداخت'), ('verify_success', 'تأیید موفق'), ('verify_failed', 'تأیید ناموفق'), ('amount_mismatch', 'عدم تطابق مبلغ'), ('expired', 'انقضای پرداخت')], max_length=30, verbose_name='نوع رویداد')),
                ('previous_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت جدید')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (تومان)')),
                ('gateway_status', models.CharField(blank=True, max_length=50, verbose_name='وضعیت درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه مرجع')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='داده تکمیلی')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='madadkar.payment', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'رویداد پرداخت',
                'verbose_name_plural': 'رویدادهای پرداخت',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['payment', 'event_kind'], name='madadkar_evt_payment_kind_idx'), models.Index(fields=['event_kind', '-created_at'], name='madadkar_evt_kind_time_idx')],
            },
        ),
    ]
