# Generated by Django 6.0.6 on 2026-06-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadkar', '0002_add_payment_event_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReconciliationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('provider_name', models.CharField(max_length=50, verbose_name='نام درگاه')),
                ('source_name', models.CharField(blank=True, max_length=180, verbose_name='نام فایل/گزارش')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('completed', 'تکمیل\u200cشده'), ('failed', 'ناموفق')], default='draft', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('mismatch_count', models.PositiveIntegerField(default=0)),
                ('missing_internal_count', models.PositiveIntegerField(default=0)),
                ('duplicate_provider_ref_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Batch تطبیق پرداخت',
                'verbose_name_plural': 'Batchهای تطبیق پرداخت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_name', 'status', '-created_at'], name='madadkar_pa_provide_1d5a7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('authority', models.CharField(blank=True, max_length=100)),
                ('provider_ref_id', models.CharField(blank=True, max_length=100)),
                ('provider_amount', models.PositiveBigIntegerField(default=0)),
                ('provider_status', models.CharField(blank=True, max_length=50)),
                ('internal_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('internal_status', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('matched', 'تطبیق موفق'), ('missing_internal', 'در سیستم داخلی پیدا نشد'), ('amount_mismatch', 'عدم تطابق مبلغ'), ('status_mismatch', 'عدم تطابق وضعیت'), ('duplicate_provider_ref', 'شناسه تکراری در گزارش درگاه')], max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='madadkar.paymentreconciliationbatch')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_items', to='madadkar.payment')),
            ],
            options={
                'verbose_name': 'ردیف تطبیق پرداخت',
                'verbose_name_plural': 'ردیف\u200cهای تطبیق پرداخت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', 'status'], name='madadkar_pa_batch_i_28afaf_idx'), models.Index(fields=['authority'], name='madadkar_pa_authori_625ada_idx'), models.Index(fields=['provider_ref_id'], name='madadkar_pa_provide_605278_idx')],
            },
        ),
    ]
