# Generated by Django 6.0.6 on 2026-06-16 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadkar', '0003_paymentreconciliationbatch_paymentreconciliationitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق'), ('expired', 'منقضی\u200cشده'), ('refunded', 'بازپرداخت\u200cشده')], db_index=True, default='pending_payment', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='event_kind',
            field=models.CharField(choices=[('created', 'ایجاد پرداخت'), ('verify_success', 'تأیید موفق'), ('verify_failed', 'تأیید ناموفق'), ('amount_mismatch', 'عدم تطابق مبلغ'), ('expired', 'انقضای پرداخت'), ('refund_requested', 'درخواست بازپرداخت'), ('refund_approved', 'تأیید بازپرداخت'), ('refund_rejected', 'رد بازپرداخت'), ('refund_completed', 'تکمیل بازپرداخت'), ('refund_failed', 'شکست بازپرداخت'), ('adjustment_applied', 'اعمال اصلاح مالی')], max_length=30, verbose_name='نوع رویداد'),
        ),
        migrations.CreateModel(
            name='CampaignFinancialAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('adjustment_type', models.CharField(choices=[('credit', 'افزایش مبلغ مؤثر'), ('debit', 'کاهش مبلغ مؤثر')], max_length=20)),
                ('status', models.CharField(choices=[('pending_review', 'در انتظار بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('applied', 'اعمال\u200cشده')], db_index=True, default='pending_review', max_length=30)),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ اصلاح')),
                ('reason', models.CharField(max_length=240, verbose_name='دلیل')),
                ('note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_adjustments', to='madadkar.campaign', verbose_name='حرکت')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_adjustments', to='madadkar.payment', verbose_name='پرداخت مرتبط')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madadkar_adjustments_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madadkar_adjustments_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اصلاح مالی کمپین',
                'verbose_name_plural': 'اصلاحات مالی کمپین',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='madadkar_adj_campaign_status_idx'), models.Index(fields=['status', '-created_at'], name='madadkar_adj_status_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='madadkar_adj_amount_min')],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ بازپرداخت')),
                ('reason', models.CharField(choices=[('duplicate_payment', 'پرداخت تکراری'), ('user_request', 'درخواست کاربر'), ('campaign_canceled', 'لغو حرکت'), ('provider_reversal', 'برگشت از سمت درگاه'), ('admin_correction', 'اصلاح ادمین'), ('other', 'سایر')], max_length=40, verbose_name='دلیل')),
                ('status', models.CharField(choices=[('pending_review', 'در انتظار بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('completed', 'تکمیل\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='pending_review', max_length=30, verbose_name='وضعیت')),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('provider_ref_id', models.CharField(blank=True, max_length=120, verbose_name='شناسه بازپرداخت درگاه')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='madadkar.payment', verbose_name='پرداخت')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madadkar_refunds_requested', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madadkar_refunds_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
            ],
            options={
                'verbose_name': 'بازپرداخت مددکار',
                'verbose_name_plural': 'بازپرداخت\u200cهای مددکار',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment', 'status'], name='madadkar_ref_payment_status_idx'), models.Index(fields=['status', '-created_at'], name='madadkar_ref_status_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='madadkar_ref_amount_min')],
            },
        ),
    ]
