# Generated by Django 6.0.6 on 2026-06-16 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadkar', '0004_alter_participation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MadadkarRiskSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('signal_type', models.CharField(choices=[('high_amount_new_user', 'مشارکت مبلغ بالا توسط کاربر جدید'), ('payment_failure_spike', 'افزایش شکست پرداخت'), ('suspicious_ip_velocity', 'سرعت غیرعادی پرداخت از IP'), ('refund_velocity', 'افزایش درخواست بازپرداخت'), ('campaign_refund_spike', 'افزایش بازپرداخت در حرکت'), ('adjustment_anomaly', 'اصلاح مالی غیرعادی')], db_index=True, max_length=60)),
                ('severity', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('critical', 'بحرانی')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'باز'), ('reviewed', 'بررسی\u200cشده'), ('dismissed', 'ردشده'), ('escalated', 'ارجاع\u200cشده')], db_index=True, default='open', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_signals', to='madadkar.campaignfinancialadjustment')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_signals', to='madadkar.campaign')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_signals', to='madadkar.payment')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_signals', to='madadkar.paymentrefund')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madadkar_reviewed_risk_signals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='madadkar_risk_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سیگنال ریسک مددکار',
                'verbose_name_plural': 'سیگنال\u200cهای ریسک مددکار',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['signal_type', 'status', '-created_at'], name='madadkar_risk_type_status_idx'), models.Index(fields=['severity', 'status', '-created_at'], name='madadkar_risk_sev_status_idx'), models.Index(fields=['user', 'status', '-created_at'], name='madadkar_risk_user_status_idx'), models.Index(fields=['campaign', 'status', '-created_at'], name='madadkar_risk_campaign_status_idx'), models.Index(fields=['ip_address', 'status', '-created_at'], name='madadkar_risk_ip_status_idx')],
            },
        ),
    ]
