# Generated by Django 6.0.6 on 2026-06-16 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadkar', '0005_madadkarrisksignal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('receipt_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('receipt_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('hash_version', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ رسید')),
                ('issued_at', models.DateTimeField(verbose_name='زمان صدور')),
                ('payment_snapshot', models.JSONField(blank=True, default=dict)),
                ('campaign_snapshot', models.JSONField(blank=True, default=dict)),
                ('donor_snapshot', models.JSONField(blank=True, default=dict)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('last_resent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donation_receipts', to='madadkar.campaign', verbose_name='حرکت')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='donation_receipt', to='madadkar.payment', verbose_name='پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madadkar_donation_receipts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رسید مشارکت مددکار',
                'verbose_name_plural': 'رسیدهای مشارکت مددکار',
                'ordering': ['-issued_at', '-created_at'],
                'indexes': [models.Index(fields=['user', '-issued_at'], name='madadkar_receipt_user_time_idx'), models.Index(fields=['campaign', '-issued_at'], name='md_receipt_camp_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='madadkar_receipt_amount_min')],
            },
        ),
    ]
