# Generated by Django 6.0.6 on 2026-06-16 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadkar', '0006_donationreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('status', models.CharField(choices=[('requested', 'درخواست\u200cشده'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('paid', 'پرداخت\u200cشده'), ('canceled', 'لغوشده')], db_index=True, default='requested', max_length=20)),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ تخصیص')),
                ('recipient_name', models.CharField(max_length=220, verbose_name='نام گیرنده')),
                ('recipient_identifier', models.CharField(blank=True, max_length=120, verbose_name='شناسه/کد گیرنده')),
                ('recipient_bank_account', models.CharField(blank=True, max_length=120, verbose_name='حساب/شبا مقصد')),
                ('recipient_snapshot', models.JSONField(blank=True, default=dict)),
                ('purpose', models.CharField(max_length=260, verbose_name='هدف تخصیص')),
                ('note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('bank_tracking_reference', models.CharField(blank=True, max_length=120)),
                ('supporting_document', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='madadkar.campaign', verbose_name='حرکت')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madadkar_disbursements_paid', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madadkar_disbursements_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madadkar_disbursements_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تخصیص مالی مددکار',
                'verbose_name_plural': 'تخصیص\u200cهای مالی مددکار',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status', '-created_at'], name='md_disb_camp_status_idx'), models.Index(fields=['status', '-created_at'], name='madadkar_disb_status_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='madadkar_disb_amount_min')],
            },
        ),
    ]
