# Generated by Django 6.0.6 on 2026-06-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadkar', '0007_campaigndisbursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadadkarFinancialControlSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('generated_for_date', models.DateField(db_index=True)),
                ('severity', models.CharField(choices=[('healthy', 'سالم'), ('watch', 'نیازمند پایش'), ('warning', 'هشدار'), ('critical', 'بحرانی')], db_index=True, default='healthy', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('controls', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('generated_by_task_id', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Snapshot کنترل مالی مددکار',
                'verbose_name_plural': 'Snapshotهای کنترل مالی مددکار',
                'ordering': ['-generated_for_date', '-created_at'],
                'indexes': [models.Index(fields=['generated_for_date', 'severity'], name='madadkar_ctrl_date_sev_idx'), models.Index(fields=['severity', '-created_at'], name='madadkar_ctrl_sev_time_idx')],
            },
        ),
    ]
