"""Django admin for Kindness Wall."""

from django.contrib import admin

from apps.kindness_wall.models import (
    KindnessBookmark,
    KindnessCategory,
    KindnessContactReveal,
    KindnessDuplicateCandidate,
    KindnessKeywordAlias,
    KindnessListing,
    KindnessListingImage,
    KindnessListingReport,
    KindnessListingTag,
    KindnessMatch,
    KindnessRiskSignal,
    KindnessTag,
)


class KindnessListingImageInline(admin.TabularInline):
    """Inline listing images."""

    model = KindnessListingImage
    extra = 0
    fields = ("image", "caption", "is_cover", "order", "is_active")


class KindnessListingTagInline(admin.TabularInline):
    """Inline listing tags."""

    model = KindnessListingTag
    extra = 0
    raw_id_fields = ("tag",)


@admin.register(KindnessCategory)
class KindnessCategoryAdmin(admin.ModelAdmin):
    """Admin tree category management."""

    list_display = ("title", "parent", "depth", "order", "is_active", "published_listings_count")
    list_filter = ("is_active", "depth", "parent")
    search_fields = ("title", "slug", "path", "description")
    readonly_fields = (
        "slug",
        "path",
        "depth",
        "listings_count",
        "published_listings_count",
        "created_at",
        "updated_at",
    )
    ordering = ("depth", "order", "title")


@admin.register(KindnessListing)
class KindnessListingAdmin(admin.ModelAdmin):
    """Admin moderation for kindness listings."""

    list_display = (
        "title",
        "listing_type",
        "category",
        "owner",
        "status",
        "province",
        "city",
        "published_at",
        "expires_at",
    )
    list_filter = ("listing_type", "status", "category", "province", "city")
    search_fields = ("title", "description", "owner__email", "contact_phone_snapshot")
    readonly_fields = (
        "slug",
        "owner_full_name_snapshot",
        "contact_phone_snapshot",
        "owner_avatar_snapshot",
        "view_count",
        "contact_reveal_count",
        "bookmark_count",
        "report_count",
        "match_generation_version",
        "last_matched_at",
        "search_document",
        "created_at",
        "updated_at",
    )
    raw_id_fields = ("owner", "reviewed_by", "category")
    inlines = [KindnessListingImageInline, KindnessListingTagInline]
    ordering = ("-created_at",)


@admin.register(KindnessTag)
class KindnessTagAdmin(admin.ModelAdmin):
    """Admin for normalized tag dictionary."""

    list_display = ("name", "normalized_name", "usage_count", "is_active")
    search_fields = ("name", "normalized_name")
    readonly_fields = ("slug", "normalized_name", "usage_count", "created_at", "updated_at")


@admin.register(KindnessKeywordAlias)
class KindnessKeywordAliasAdmin(admin.ModelAdmin):
    """Admin for synonym dictionary used by matching."""

    list_display = ("keyword", "alias", "is_active")
    search_fields = ("keyword", "alias", "normalized_keyword", "normalized_alias")
    readonly_fields = ("normalized_keyword", "normalized_alias", "created_at", "updated_at")


@admin.register(KindnessMatch)
class KindnessMatchAdmin(admin.ModelAdmin):
    """Read-focused admin for generated matches."""

    list_display = (
        "source_listing",
        "target_listing",
        "score",
        "status",
        "algorithm_version",
        "generated_at",
    )
    list_filter = ("status", "algorithm_version")
    search_fields = ("source_listing__title", "target_listing__title", "explanation")
    readonly_fields = [field.name for field in KindnessMatch._meta.fields]
    raw_id_fields = ("source_listing", "target_listing", "dismissed_by")

    def has_add_permission(self, request) -> bool:
        """Matches are generated by the matching engine."""
        return False

    def has_change_permission(self, request, obj=None) -> bool:
        """Match mutation should go through services."""
        return False

    def has_delete_permission(self, request, obj=None) -> bool:
        """Match evidence should be preserved."""
        return False


@admin.register(KindnessContactReveal)
class KindnessContactRevealAdmin(admin.ModelAdmin):
    """Read-only admin for contact reveal audit records."""

    list_display = (
        "listing",
        "viewer",
        "listing_owner",
        "phone_snapshot",
        "ip_address",
        "created_at",
    )
    list_filter = ("created_at", "ip_address")
    search_fields = ("listing__title", "viewer__email", "listing_owner__email", "phone_snapshot")
    readonly_fields = [field.name for field in KindnessContactReveal._meta.fields]

    def has_add_permission(self, request) -> bool:
        """Contact reveal records are service-created."""
        return False

    def has_change_permission(self, request, obj=None) -> bool:
        """Contact reveal records are immutable from admin."""
        return False

    def has_delete_permission(self, request, obj=None) -> bool:
        """Contact reveal records should not be deleted."""
        return False


@admin.register(KindnessListingReport)
class KindnessListingReportAdmin(admin.ModelAdmin):
    """Admin report review queue."""

    list_display = ("listing", "reported_by", "reason", "status", "created_at", "reviewed_at")
    list_filter = ("status", "reason")
    search_fields = ("listing__title", "reported_by__email", "description")
    raw_id_fields = ("listing", "reported_by", "reviewed_by")


@admin.register(KindnessBookmark)
class KindnessBookmarkAdmin(admin.ModelAdmin):
    """Read-only bookmark admin."""

    list_display = ("user", "listing", "created_at")
    search_fields = ("user__email", "listing__title")
    readonly_fields = [field.name for field in KindnessBookmark._meta.fields]


@admin.register(KindnessDuplicateCandidate)
class KindnessDuplicateCandidateAdmin(admin.ModelAdmin):
    """Admin duplicate candidate review."""

    list_display = ("listing", "candidate_listing", "score", "status", "created_at")
    list_filter = ("status",)
    search_fields = ("listing__title", "candidate_listing__title", "reason")


admin.site.register(KindnessListingImage)
admin.site.register(KindnessListingTag)


@admin.register(KindnessRiskSignal)
class KindnessRiskSignalAdmin(admin.ModelAdmin):
    """Admin review queue for Kindness Wall risk signals."""

    list_display = ("signal_type", "severity", "status", "user", "listing", "created_at")
    list_filter = ("signal_type", "severity", "status")
    search_fields = ("description", "user__email", "listing__title")
    raw_id_fields = ("user", "listing", "reviewed_by")
    readonly_fields = ("created_at", "updated_at")
