"""Facade سازگاری — یافتۀ P3-16 فاز 8 (تفکیک فایل غول‌پیکر).

پیاده‌سازی در ماژول‌های دامنه‌ای این اپ است (views_common + گروه‌ها)؛ این فایل فقط باز‌صاد می‌کند تا هیچ import بیرونی‌ای (urls/tests/سایر اپ‌ها) نشکند و URLها تضمیناً ثابت بمانند. کد جدیدِ گروه‌محور را از همان ماژول دامنه‌ای import کنید، نه از اینجا.
"""

from __future__ import annotations

from .views_admin import (
    KindnessAdminAnalyticsView,
    KindnessAdminCategoryDetailView,
    KindnessAdminCategoryListCreateView,
    KindnessAdminContactRevealListView,
    KindnessAdminDuplicateCandidateListView,
    KindnessAdminDuplicateCandidateReviewView,
    KindnessAdminListingApproveView,
    KindnessAdminListingDetailView,
    KindnessAdminListingExportView,
    KindnessAdminListingListView,
    KindnessAdminListingRejectView,
    KindnessAdminListingRestoreView,
    KindnessAdminListingSuspendView,
    KindnessAdminMatchDetailView,
    KindnessAdminMatchListView,
    KindnessAdminReportExportView,
    KindnessAdminReportListView,
    KindnessAdminReportReviewView,
)
from .views_common import (
    ANALYTICS_RESPONSE,
    CATEGORY_LIST_RESPONSE,
    CONTACT_REVEAL_RESPONSE,
    EMPTY_RESPONSE,
    ERROR_RESPONSE,
    LISTING_DETAIL_RESPONSE,
    LISTING_LIST_RESPONSE,
    MATCH_LIST_RESPONSE,
    REPORT_RESPONSE,
    TAG_ADMIN,
    TAG_PUBLIC,
    TAG_USER,
    USER_LISTING_DETAIL_RESPONSE,
    _service_error_response,
)
from .views_engagement import (
    KindnessBookmarkView,
    KindnessContactRevealView,
    KindnessListingReportCreateView,
    KindnessMatchContactedView,
    KindnessMatchDismissView,
)
from .views_public import (
    KindnessCategoryPublicListView,
    KindnessListingPublicDetailView,
    KindnessListingPublicListView,
    KindnessListingPublicMatchesView,
)
from .views_user import (
    KindnessUserBookmarkListView,
    KindnessUserListingCloseView,
    KindnessUserListingDetailView,
    KindnessUserListingListCreateView,
    KindnessUserListingRenewView,
    KindnessUserListingSubmitView,
    KindnessUserMatchListView,
)

__all__ = [
    "ANALYTICS_RESPONSE",
    "CATEGORY_LIST_RESPONSE",
    "CONTACT_REVEAL_RESPONSE",
    "EMPTY_RESPONSE",
    "ERROR_RESPONSE",
    "LISTING_DETAIL_RESPONSE",
    "LISTING_LIST_RESPONSE",
    "MATCH_LIST_RESPONSE",
    "REPORT_RESPONSE",
    "TAG_ADMIN",
    "TAG_PUBLIC",
    "TAG_USER",
    "USER_LISTING_DETAIL_RESPONSE",
    "KindnessAdminAnalyticsView",
    "KindnessAdminCategoryDetailView",
    "KindnessAdminCategoryListCreateView",
    "KindnessAdminContactRevealListView",
    "KindnessAdminDuplicateCandidateListView",
    "KindnessAdminDuplicateCandidateReviewView",
    "KindnessAdminListingApproveView",
    "KindnessAdminListingDetailView",
    "KindnessAdminListingExportView",
    "KindnessAdminListingListView",
    "KindnessAdminListingRejectView",
    "KindnessAdminListingRestoreView",
    "KindnessAdminListingSuspendView",
    "KindnessAdminMatchDetailView",
    "KindnessAdminMatchListView",
    "KindnessAdminReportExportView",
    "KindnessAdminReportListView",
    "KindnessAdminReportReviewView",
    "KindnessBookmarkView",
    "KindnessCategoryPublicListView",
    "KindnessContactRevealView",
    "KindnessListingPublicDetailView",
    "KindnessListingPublicListView",
    "KindnessListingPublicMatchesView",
    "KindnessListingReportCreateView",
    "KindnessMatchContactedView",
    "KindnessMatchDismissView",
    "KindnessUserBookmarkListView",
    "KindnessUserListingCloseView",
    "KindnessUserListingDetailView",
    "KindnessUserListingListCreateView",
    "KindnessUserListingRenewView",
    "KindnessUserListingSubmitView",
    "KindnessUserMatchListView",
    "_service_error_response",
]
