# Generated by Django 6.0.5 on 2026-05-21 14:46

import apps.r4j.models
import apps.r4j.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='R4JCriminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('first_name', models.CharField(max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('slug', models.SlugField(blank=True, help_text='در صورت خالی بودن، خودکار از نام ساخته می\u200cشود.', max_length=200, unique=True, verbose_name='شناسه URL')),
                ('national_code', models.CharField(blank=True, help_text='برای مجرمین غیرایرانی خالی می\u200cماند.', max_length=10, null=True, validators=[apps.r4j.validators.validate_iranian_national_code], verbose_name='کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('unknown', 'نامشخص')], default='unknown', max_length=10, verbose_name='جنسیت')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='کشور')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('crimes_summary', models.TextField(blank=True, verbose_name='خلاصه جرائم')),
                ('other_info', models.TextField(blank=True, help_text='متن آزاد برای ثبت هر اطلاعات تکمیلی.', verbose_name='سایر اطلاعات')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('total_bounty_toman', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مجموع جوایز (تومان)')),
                ('bounties_count', models.PositiveIntegerField(default=0, verbose_name='تعداد جوایز')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r4j_created_criminals', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'مجرم',
                'verbose_name_plural': 'مجرمین',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='R4JBounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('amount_toman', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(50000)], verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('cancel_requested', 'درخواست لغو'), ('canceled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان درخواست لغو')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='r4j_bounties', to=settings.AUTH_USER_MODEL, verbose_name='تعهدکننده')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bounties', to='r4j.r4jcriminal', verbose_name='مجرم')),
            ],
            options={
                'verbose_name': 'جایزه',
                'verbose_name_plural': 'جوایز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='R4JCriminalAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('alias', models.CharField(max_length=200, verbose_name='نام مستعار')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='r4j.r4jcriminal', verbose_name='مجرم')),
            ],
            options={
                'verbose_name': 'نام مستعار',
                'verbose_name_plural': 'نام\u200cهای مستعار',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='R4JCriminalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('file', models.FileField(upload_to=apps.r4j.models._criminal_attachment_upload_path, validators=[apps.r4j.validators.validate_attachment_size], verbose_name='فایل')),
                ('kind', models.CharField(choices=[('document', 'سند'), ('image', 'تصویر'), ('video', 'ویدیو'), ('audio', 'صوت'), ('other', 'سایر')], default='document', max_length=20, verbose_name='نوع')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_public', models.BooleanField(default=False, verbose_name='نمایش عمومی')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='r4j.r4jcriminal', verbose_name='مجرم')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r4j_uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'سند مجرم',
                'verbose_name_plural': 'اسناد مجرمین',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='R4JCriminalFieldVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('field_name', models.CharField(max_length=50, verbose_name='نام فیلد')),
                ('is_public', models.BooleanField(default=True, verbose_name='نمایش عمومی')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_visibility', to='r4j.r4jcriminal', verbose_name='مجرم')),
            ],
            options={
                'verbose_name': 'تنظیمات نمایش فیلد',
                'verbose_name_plural': 'تنظیمات نمایش فیلدها',
                'ordering': ['criminal_id', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='R4JCriminalPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='برچسب')),
                ('number', models.CharField(max_length=30, verbose_name='شماره')),
                ('is_public', models.BooleanField(default=False, verbose_name='نمایش عمومی')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='r4j.r4jcriminal', verbose_name='مجرم')),
            ],
            options={
                'verbose_name': 'شماره تماس مجرم',
                'verbose_name_plural': 'شماره\u200cهای تماس مجرمین',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='R4JCriminalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ImageField(upload_to=apps.r4j.models._criminal_photo_upload_path, validators=[apps.r4j.validators.validate_photo_size, apps.r4j.validators.validate_photo_extension], verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='توضیح کوتاه')),
                ('is_primary', models.BooleanField(default=False, verbose_name='عکس اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='r4j.r4jcriminal', verbose_name='مجرم')),
            ],
            options={
                'verbose_name': 'عکس مجرم',
                'verbose_name_plural': 'عکس\u200cهای مجرمین',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='R4JCriminalSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('platform', models.CharField(choices=[('telegram', 'تلگرام'), ('twitter_x', 'X (توییتر)'), ('instagram', 'اینستاگرام'), ('linkedin', 'لینکدین'), ('facebook', 'فیسبوک'), ('tiktok', 'تیک\u200cتاک'), ('truth_social', 'Truth Social'), ('youtube', 'یوتیوب'), ('website', 'وبسایت شخصی'), ('other', 'سایر')], max_length=20, verbose_name='پلتفرم')),
                ('handle_or_url', models.CharField(max_length=255, verbose_name='هندل یا URL')),
                ('is_public', models.BooleanField(default=True, verbose_name='نمایش عمومی')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='r4j.r4jcriminal', verbose_name='مجرم')),
            ],
            options={
                'verbose_name': 'حساب شبکه اجتماعی مجرم',
                'verbose_name_plural': 'حساب\u200cهای شبکه اجتماعی مجرمین',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='R4JReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, help_text='متن آزاد گزارش\u200cدهنده در صورت نیاز.', verbose_name='یادداشت گزارش\u200cدهنده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید کامل'), ('partially_approved', 'تأیید جزئی'), ('rejected', 'رد شده'), ('cancel_requested', 'درخواست لغو'), ('canceled', 'لغو شده')], default='pending', max_length=30, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان درخواست لغو')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='r4j.r4jcriminal', verbose_name='مجرم')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r4j_reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='r4j_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
            ],
            options={
                'verbose_name': 'گزارش جامعه',
                'verbose_name_plural': 'گزارشات جامعه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='R4JReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('file', models.FileField(upload_to=apps.r4j.models._report_attachment_upload_path, validators=[apps.r4j.validators.validate_attachment_size], verbose_name='فایل')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان')),
                ('kind', models.CharField(choices=[('document', 'سند'), ('image', 'تصویر'), ('video', 'ویدیو'), ('audio', 'صوت'), ('other', 'سایر')], default='document', max_length=20, verbose_name='نوع')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='r4j.r4jreport', verbose_name='گزارش')),
            ],
            options={
                'verbose_name': 'ضمیمه گزارش',
                'verbose_name_plural': 'ضمائم گزارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='R4JReportFieldChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('field_name', models.CharField(max_length=100, verbose_name='نام فیلد')),
                ('suggested_value', models.TextField(verbose_name='مقدار پیشنهادی')),
                ('current_value_snapshot', models.TextField(blank=True, verbose_name='مقدار فعلی هنگام گزارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='r4j.r4jreport', verbose_name='گزارش')),
            ],
            options={
                'verbose_name': 'پیشنهاد تغییر فیلد',
                'verbose_name_plural': 'پیشنهادات تغییر فیلد',
                'ordering': ['report_id', 'field_name'],
            },
        ),
        migrations.AddIndex(
            model_name='r4jcriminal',
            index=models.Index(fields=['is_published', 'is_active'], name='r4j_r4jcrim_is_publ_cfdff0_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminal',
            index=models.Index(fields=['last_name', 'first_name'], name='r4j_r4jcrim_last_na_ab7c65_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminal',
            index=models.Index(fields=['country', 'province', 'city'], name='r4j_r4jcrim_country_1174c2_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminal',
            index=models.Index(fields=['-total_bounty_toman'], name='r4j_r4jcrim_total_b_e4275a_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jbounty',
            index=models.Index(fields=['criminal', 'status'], name='r4j_r4jboun_crimina_8c53e3_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jbounty',
            index=models.Index(fields=['user', 'status'], name='r4j_r4jboun_user_id_aa8a32_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jbounty',
            index=models.Index(fields=['status'], name='r4j_r4jboun_status_a0793e_idx'),
        ),
        migrations.AddConstraint(
            model_name='r4jbounty',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('criminal', 'user'), name='uniq_r4j_active_bounty_per_user_criminal'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminalalias',
            index=models.Index(fields=['alias'], name='r4j_r4jcrim_alias_17a07c_idx'),
        ),
        migrations.AddConstraint(
            model_name='r4jcriminalalias',
            constraint=models.UniqueConstraint(fields=('criminal', 'alias'), name='uniq_r4j_alias_per_criminal'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminalattachment',
            index=models.Index(fields=['criminal', 'is_public', 'kind'], name='r4j_r4jcrim_crimina_075dc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='r4jcriminalfieldvisibility',
            constraint=models.UniqueConstraint(fields=('criminal', 'field_name'), name='uniq_r4j_field_visibility'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminalphone',
            index=models.Index(fields=['criminal', 'is_public'], name='r4j_r4jcrim_crimina_698ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminalphoto',
            index=models.Index(fields=['criminal', 'is_primary'], name='r4j_r4jcrim_crimina_567730_idx'),
        ),
        migrations.AddConstraint(
            model_name='r4jcriminalphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('criminal',), name='uniq_r4j_primary_photo_per_criminal'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminalsocial',
            index=models.Index(fields=['criminal', 'is_public'], name='r4j_r4jcrim_crimina_8b84b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='r4jcriminalsocial',
            constraint=models.UniqueConstraint(fields=('criminal', 'platform', 'handle_or_url'), name='uniq_r4j_social_per_criminal'),
        ),
        migrations.AddIndex(
            model_name='r4jreport',
            index=models.Index(fields=['criminal', 'status'], name='r4j_r4jrepo_crimina_21b4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jreport',
            index=models.Index(fields=['submitted_by', 'status'], name='r4j_r4jrepo_submitt_b6a38f_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jreport',
            index=models.Index(fields=['status'], name='r4j_r4jrepo_status_092c49_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jreportattachment',
            index=models.Index(fields=['report', 'kind'], name='r4j_r4jrepo_report__835572_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jreportfieldchange',
            index=models.Index(fields=['report', 'status'], name='r4j_r4jrepo_report__c05a7b_idx'),
        ),
    ]
