# Generated by Django 6.0.5 on 2026-06-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r4j', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r4jcriminalattachment',
            name='kind',
            field=models.CharField(choices=[('image', 'تصویر'), ('document', 'سند'), ('video', 'ویدئو'), ('audio', 'صدا'), ('other', 'سایر')], default='document', max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='r4jcriminalsocial',
            name='platform',
            field=models.CharField(choices=[('telegram', 'تلگرام'), ('twitter_x', 'توییتر / ایکس'), ('instagram', 'اینستاگرام'), ('linkedin', 'لینکدین'), ('facebook', 'فیسبوک'), ('tiktok', 'تیک\u200cتاک'), ('truth_social', 'تروث سوشال'), ('youtube', 'یوتیوب'), ('website', 'وب\u200cسایت'), ('other', 'سایر')], max_length=20, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='r4jreport',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('partially_approved', 'تأیید جزئی'), ('rejected', 'رد شده'), ('cancel_requested', 'درخواست لغو'), ('canceled', 'لغو شده')], default='pending', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='r4jreportattachment',
            name='kind',
            field=models.CharField(choices=[('image', 'تصویر'), ('document', 'سند'), ('video', 'ویدئو'), ('audio', 'صدا'), ('other', 'سایر')], default='document', max_length=20, verbose_name='نوع'),
        ),
    ]
