# Generated by Django 6.0.5 on 2026-06-10 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r4j', '0002_sync_choice_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='r4jbounty',
            name='r4j_r4jboun_crimina_8c53e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='r4jbounty',
            name='r4j_r4jboun_user_id_aa8a32_idx',
        ),
        migrations.RemoveIndex(
            model_name='r4jbounty',
            name='r4j_r4jboun_status_a0793e_idx',
        ),
        migrations.RemoveIndex(
            model_name='r4jcriminal',
            name='r4j_r4jcrim_is_publ_cfdff0_idx',
        ),
        migrations.RemoveIndex(
            model_name='r4jreport',
            name='r4j_r4jrepo_crimina_21b4b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='r4jreport',
            name='r4j_r4jrepo_submitt_b6a38f_idx',
        ),
        migrations.RemoveIndex(
            model_name='r4jreport',
            name='r4j_r4jrepo_status_092c49_idx',
        ),
        migrations.AddIndex(
            model_name='r4jbounty',
            index=models.Index(fields=['criminal', 'status', '-created_at'], name='r4j_r4jboun_crimina_3e6366_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jbounty',
            index=models.Index(fields=['user', 'status', '-created_at'], name='r4j_r4jboun_user_id_1b01ea_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jbounty',
            index=models.Index(fields=['status', '-created_at'], name='r4j_r4jboun_status_ee245f_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminal',
            index=models.Index(fields=['is_published', 'is_active', '-created_at'], name='r4j_r4jcrim_is_publ_e3a3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminal',
            index=models.Index(fields=['gender', 'is_published', 'is_active'], name='r4j_r4jcrim_gender_4458f3_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminalphone',
            index=models.Index(fields=['number'], name='r4j_r4jcrim_number_490ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jcriminalsocial',
            index=models.Index(fields=['platform', 'is_public'], name='r4j_r4jcrim_platfor_855771_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jreport',
            index=models.Index(fields=['criminal', 'status', '-created_at'], name='r4j_r4jrepo_crimina_8eb9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jreport',
            index=models.Index(fields=['submitted_by', 'status', '-created_at'], name='r4j_r4jrepo_submitt_8d7063_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jreport',
            index=models.Index(fields=['status', '-created_at'], name='r4j_r4jrepo_status_8edc4a_idx'),
        ),
    ]
