# Generated by Django 6.0.6 on 2026-06-18 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r4j', '0003_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='r4jcriminalattachment',
            name='file_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256'),
        ),
        migrations.AddField(
            model_name='r4jcriminalattachment',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='حجم فایل'),
        ),
        migrations.AddField(
            model_name='r4jreportattachment',
            name='file_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256'),
        ),
        migrations.AddField(
            model_name='r4jreportattachment',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='حجم فایل'),
        ),
        migrations.CreateModel(
            name='R4JEvidenceCustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('event_type', models.CharField(choices=[('uploaded', 'آپلود شد'), ('hashed', 'هش شد'), ('reviewed', 'بررسی شد'), ('transferred', 'منتقل شد'), ('rejected', 'رد شد'), ('deleted', 'حذف شد')], db_index=True, max_length=30)),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r4j_evidence_custody_events', to=settings.AUTH_USER_MODEL)),
                ('criminal_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='r4j.r4jcriminalattachment')),
                ('report_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='r4j.r4jreportattachment')),
            ],
            options={
                'verbose_name': 'رویداد زنجیره نگهداری شواهد R4J',
                'verbose_name_plural': 'رویدادهای زنجیره نگهداری شواهد R4J',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='r4j_r4jevid_event_t_85db32_idx'), models.Index(fields=['file_sha256'], name='r4j_r4jevid_file_sh_8bfb2f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('criminal_attachment__isnull', False), ('report_attachment__isnull', True)), models.Q(('criminal_attachment__isnull', True), ('report_attachment__isnull', False)), _connector='OR'), name='r4j_custody_one_evidence_target')],
            },
        ),
    ]
