# Generated by Django 6.0.6 on 2026-06-18 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r4j', '0004_r4jcriminalattachment_file_sha256_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='R4JInvestigationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('case_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='شماره پرونده')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('triaged', 'تریاژ شده'), ('assigned', 'ارجاع شده'), ('investigating', 'در حال بررسی'), ('waiting_for_evidence', 'در انتظار مدرک'), ('escalated', 'ارجاع فوری'), ('resolved', 'حل شده'), ('rejected', 'رد شده'), ('closed', 'بسته شده')], db_index=True, default='new', max_length=40, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('critical', 'بحرانی')], db_index=True, default='medium', max_length=20, verbose_name='اولویت')),
                ('severity', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('critical', 'بحرانی')], db_index=True, default='medium', max_length=20, verbose_name='شدت')),
                ('evidence_completeness_score', models.PositiveSmallIntegerField(default=0, verbose_name='امتیاز تکمیل مدارک')),
                ('triaged_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تریاژ')),
                ('first_response_due_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='مهلت پاسخ اولیه')),
                ('resolution_due_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='مهلت حل پرونده')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بستن')),
                ('closure_reason', models.TextField(blank=True, verbose_name='دلیل بستن / رد / حل')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_r4j_investigation_cases', to=settings.AUTH_USER_MODEL, verbose_name='مسئول پرونده')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_r4j_investigation_cases', to=settings.AUTH_USER_MODEL, verbose_name='بسته\u200cکننده')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigation_cases', to='r4j.r4jcriminal', verbose_name='مجرم')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investigation_case', to='r4j.r4jreport', verbose_name='گزارش')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_r4j_investigation_cases', to=settings.AUTH_USER_MODEL, verbose_name='تریاژکننده')),
            ],
            options={
                'verbose_name': 'پرونده عملیاتی R4J',
                'verbose_name_plural': 'پرونده\u200cهای عملیاتی R4J',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='R4JCaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('event_type', models.CharField(choices=[('created', 'ایجاد شد'), ('triaged', 'تریاژ شد'), ('assigned', 'ارجاع شد'), ('priority_changed', 'اولویت تغییر کرد'), ('evidence_requested', 'مدرک بیشتر درخواست شد'), ('escalated', 'ارجاع فوری شد'), ('resolved', 'حل شد'), ('rejected', 'رد شد'), ('closed', 'بسته شد'), ('reopened', 'بازگشایی شد')], db_index=True, max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=40)),
                ('to_status', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r4j_case_events', to=settings.AUTH_USER_MODEL, verbose_name='عامل')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='r4j.r4jinvestigationcase', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'رویداد پرونده R4J',
                'verbose_name_plural': 'رویدادهای پرونده R4J',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='r4jinvestigationcase',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='r4j_r4jinve_status_d91ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jinvestigationcase',
            index=models.Index(fields=['criminal', 'status', '-created_at'], name='r4j_r4jinve_crimina_b91f46_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jinvestigationcase',
            index=models.Index(fields=['assigned_to', 'status', '-created_at'], name='r4j_r4jinve_assigne_803a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jinvestigationcase',
            index=models.Index(fields=['priority', 'severity', '-created_at'], name='r4j_r4jinve_priorit_2d62ba_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jcaseevent',
            index=models.Index(fields=['case', 'created_at'], name='r4j_r4jcase_case_id_58270d_idx'),
        ),
        migrations.AddIndex(
            model_name='r4jcaseevent',
            index=models.Index(fields=['event_type', '-created_at'], name='r4j_r4jcase_event_t_9a5c0b_idx'),
        ),
    ]
