# Generated by Django 6.0.8 on 2026-08-28 14:54

import apps.core.fields
import apps.r4j.models
import apps.r4j.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r4j', '0008_field_visibility_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r4jcriminalphoto',
            name='image',
            field=apps.core.fields.SanitizedImageField(help_text='متادیتای تصویر (از جمله مختصات GPS در EXIF) هنگام ذخیره حذف می\u200cشود.', upload_to=apps.r4j.models._criminal_photo_upload_path, validators=[apps.r4j.validators.validate_photo_size, apps.r4j.validators.validate_photo_extension], verbose_name='تصویر'),
        ),
    ]
