# Generated by Django 6.0.5 on 2026-05-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='شماره موبایل تأیید شده'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='در فرمت E.164 ذخیره می\u200cشود (مثلاً +989120000000).', max_length=20, null=True, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_identifier',
            field=models.CharField(choices=[('email', 'ایمیل'), ('phone', 'شماره موبایل')], default='email', help_text='نوع شناسه\u200cای که کاربر در ابتدا با آن ثبت\u200cنام کرده است.', max_length=10, verbose_name='شناسه اصلی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='شماره\u200cی تماس پروفایل (متفاوت از شماره\u200cی auth کاربر).', max_length=20, verbose_name='شماره تماس اضافی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone_number__isnull', False), _connector='OR'), name='user_must_have_email_or_phone'),
        ),
    ]
