# Generated by Django 6.0.5 on 2026-05-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_move_phone_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
