# Generated by Django 6.0.5 on 2026-05-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otpcode',
            name='authenticat_user_id_d47289_idx',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='code_hash',
            field=models.CharField(default='', help_text='SHA-256 از (secret_salt + code) — کد plain هرگز ذخیره نمی\u200cشود.', max_length=64, verbose_name='هش کد'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='identifier_kind',
            field=models.CharField(choices=[('email', 'ایمیل'), ('phone', 'شماره موبایل')], default='email', max_length=10, verbose_name='نوع شناسه'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='identifier_value',
            field=models.CharField(default='', help_text='ایمیل نرمالایز شده یا شماره در فرمت E.164.', max_length=254, verbose_name='مقدار شناسه'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('signup', 'ثبت\u200cنام'), ('login', 'ورود'), ('identifier_add', 'افزودن شناسه جدید'), ('email_verification', 'تأیید ایمیل'), ('password_reset', 'بازیابی رمز عبور')], max_length=30, verbose_name='هدف'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['identifier_kind', 'identifier_value', 'purpose', 'is_used'], name='idx_otp_lookup_active'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['expires_at'], name='idx_otp_expires_at'),
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='code',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='user',
        ),
    ]
