# Generated by Django 6.0.5 on 2026-05-20 10:03

import apps.authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_refactor_otpcode"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.authentication.managers.UserManager()),
            ],
        ),
    ]