# Generated by Django 6.0.6 on 2026-06-17 17:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('refresh_jti', models.CharField(db_index=True, max_length=120, unique=True)),
                ('device_label', models.CharField(blank=True, max_length=160)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fingerprint_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_auth_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نشست احراز هویت',
                'verbose_name_plural': 'نشست\u200cهای احراز هویت',
                'ordering': ['-last_seen_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_revoked', '-last_seen_at'], name='authenticat_user_id_08f73f_idx'), models.Index(fields=['fingerprint_hash', 'is_revoked'], name='authenticat_fingerp_ed50dd_idx')],
            },
        ),
    ]
