# Generated by Django 6.0.6 on 2026-06-17 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_authsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRiskSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('signal_type', models.CharField(choices=[('new_device', 'دستگاه جدید'), ('new_ip', 'IP جدید'), ('failed_login_spike', 'افزایش تلاش ورود ناموفق'), ('session_revoke_spike', 'افزایش لغو نشست')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('critical', 'بحرانی')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'باز'), ('reviewed', 'بررسی\u200cشده'), ('dismissed', 'ردشده'), ('escalated', 'ارجاع\u200cشده')], db_index=True, default='open', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_auth_risk_signals', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_signals', to='authentication.authsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_risk_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سیگنال ریسک احراز هویت',
                'verbose_name_plural': 'سیگنال\u200cهای ریسک احراز هویت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['signal_type', 'status', '-created_at'], name='authenticat_signal__e2dd70_idx'), models.Index(fields=['user', 'status', '-created_at'], name='authenticat_user_id_baa732_idx'), models.Index(fields=['severity', 'status', '-created_at'], name='authenticat_severit_9380eb_idx')],
            },
        ),
    ]
