# Generated by Django 6.0.8 on 2026-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_authrisksignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='code_salt',
            field=models.CharField(blank=True, default='', help_text='نمک تصادفی مخصوص همین رکورد. بدون آن، کد یکسان همیشه هش یکسان تولید می\u200cکند و کسی که دسترسی خواندن به دیتابیس دارد می\u200cتواند OTPهای هم\u200cمقدار را در کل جدول به هم مرتبط کند.', max_length=32, verbose_name='نمک هش'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code_hash',
            field=models.CharField(default='', help_text='HMAC-SHA256 روی (SECRET_KEY, salt|context|code) — کد plain هرگز ذخیره نمی\u200cشود.', max_length=64, verbose_name='هش کد'),
        ),
    ]
