# Generated by Django 6.0.6 on 2026-06-12 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=160)),
                ('aggregate_type', models.CharField(blank=True, max_length=120)),
                ('aggregate_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'معمولی'), ('high', 'زیاد'), ('urgent', 'فوری')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در انتظار ارسال'), ('processing', 'در حال پردازش'), ('sent', 'ارسال\u200cشده'), ('partial', 'ارسال ناقص'), ('failed', 'ناموفق'), ('cancelled', 'لغوشده')], db_index=True, default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('channel', models.CharField(choices=[('in_app', 'داخل سامانه'), ('email', 'ایمیل'), ('sms', 'پیامک'), ('webhook', 'وب\u200cهوک')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق'), ('skipped', 'ردشده'), ('read', 'خوانده\u200cشده')], db_index=True, default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=260)),
                ('body', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('event_type', models.CharField(max_length=160)),
                ('channel', models.CharField(choices=[('in_app', 'داخل سامانه'), ('email', 'ایمیل'), ('sms', 'پیامک'), ('webhook', 'وب\u200cهوک')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('channel', models.CharField(choices=[('in_app', 'داخل سامانه'), ('email', 'ایمیل'), ('sms', 'پیامک'), ('webhook', 'وب\u200cهوک')], max_length=20)),
                ('subject_template', models.CharField(blank=True, max_length=260)),
                ('body_template', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('code', 'channel'), name='uniq_notification_template_code_channel')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['status', 'next_retry_at', '-created_at'], name='notificatio_status_5b5ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_type', '-created_at'], name='notificatio_event_t_d4510d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['recipient', 'channel', 'status', '-created_at'], name='notificatio_recipie_e06306_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['event', 'channel'], name='notificatio_event_i_df69f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'recipient', 'channel'), name='uniq_notification_delivery_event_recipient_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'event_type', 'channel'], name='notificatio_user_id_84aebf_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'event_type', 'channel'), name='uniq_notification_preference'),
        ),
    ]
