# Generated by Django 6.0.6 on 2026-06-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='code',
            field=models.SlugField(max_length=120),
        ),
    ]
