# Generated by Django 6.0.5 on 2026-05-20 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('action', models.CharField(max_length=100, verbose_name='عملیات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('request_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه درخواست')),
                ('resource_type', models.CharField(max_length=100, verbose_name='نوع منبع')),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه منبع')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='تغییرات')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='داده اضافی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='audit_logs__action_235999_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs__resourc_760a22_idx'), models.Index(fields=['request_id'], name='audit_logs__request_0d533f_idx')],
            },
        ),
    ]
