# Generated by Django 6.0.5 on 2026-06-10 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs__action_235999_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs__resourc_760a22_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, max_length=10, verbose_name='متد HTTP'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, max_length=512, verbose_name='مسیر درخواست'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='شناسه درخواست'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='audit_logs__action_7c186a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id', '-created_at'], name='audit_logs__resourc_f1d478_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-created_at'], name='audit_logs__ip_addr_52c8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['method', 'path'], name='audit_logs__method_b6b11c_idx'),
        ),
    ]
