# Generated by Django 6.0.6 on 2026-06-16 10:51

import hashlib
import json

from django.conf import settings
from django.db import migrations, models


def _compute_hash(audit, previous_hash: str) -> str:
    payload = {
        "hash_version": audit.hash_version,
        "previous_hash": previous_hash,
        "user_id": audit.user_id,
        "action": audit.action,
        "ip_address": audit.ip_address,
        "request_id": audit.request_id,
        "user_agent": audit.user_agent,
        "path": audit.path,
        "method": audit.method,
        "resource_type": audit.resource_type,
        "resource_id": audit.resource_id,
        "changes": audit.changes,
        "extra_data": audit.extra_data,
    }
    encoded = json.dumps(payload, sort_keys=True, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def backfill_audit_hash_chain(apps, schema_editor):
    """Backfill tamper-evident hash chain for existing audit logs."""
    AuditLog = apps.get_model("audit_logs", "AuditLog")
    previous_hash = "0" * 64
    for audit in AuditLog.objects.order_by("created_at", "id"):
        event_hash = _compute_hash(audit, previous_hash)
        AuditLog.objects.filter(pk=audit.pk).update(previous_hash=previous_hash, event_hash=event_hash, hash_version=1)
        previous_hash = event_hash


class Migration(migrations.Migration):
    dependencies = [
        ("audit_logs", "0002_forensic_metadata_and_immutability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="event_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name="هش رویداد"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="hash_version",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="نسخه هش"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name="هش قبلی"),
        ),
        migrations.RunPython(backfill_audit_hash_chain, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="auditlog",
            name="event_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name="هش رویداد"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["previous_hash"], name="audit_logs__previou_93ee65_idx"),
        ),
    ]
